---
settings:
  name: StorageGRID 11.5
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: 全國11月5日文件StorageGRID
    url: "/index.html"
  - section: release-notes
  - title: 開始使用
    entries:
    - section: primer
    - section: network
  - title: 安裝及升級軟體
    entries:
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: 安裝及維護硬體
    entries:
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: 設定與管理
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: 使用StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: 監控及疑難排解
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: 維護
    entries:
    - section: expand
    - section: maintain
  - title: 其他版本
    url: "/earlier-versions.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
