---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: 在規劃升級StorageGRID 至版本的過程中、您必須根據升級所需的時間來考慮何時進行升級。您也必須知道在升級的每個階段中、可以執行哪些作業、也不能執行哪些作業。 
---
= 預估完成升級的時間
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在規劃升級StorageGRID 至版本的過程中、您必須根據升級所需的時間來考慮何時進行升級。您也必須知道在升級的每個階段中、可以執行哪些作業、也不能執行哪些作業。

.關於這項工作
完成升級所需的時間StorageGRID 取決於多種因素、例如用戶端負載和硬體效能。

下表摘要說明主要的升級工作、並列出每項工作所需的大約時間。表格後的步驟提供您可用來預估系統升級時間的指示。


IMPORTANT: 從StorageGRID 還原11.4升級至11.5期間、儲存節點上的Cassandra資料庫表格將會升級。「*升級資料庫*」工作會在背景執行、但可能需要大量的時間才能完成。在升級資料庫的過程中、您可以安全地使用新功能、套用修補程式、以及執行節點還原作業。不過、您可能無法執行其他維護程序。


NOTE: 如果迫切需要擴充、請在升級至11.5之前執行擴充。

[cols="1a,1a,1a,a"]
|===
| 升級工作 | 說明 | 大約所需時間 | 在此工作期間 


 a| 
啟動升級服務
 a| 
執行升級預先檢查、散佈軟體檔案、並啟動升級服務。
 a| 
每個網格節點3分鐘、除非報告驗證錯誤
 a| 
視需要、您可以在排程的升級維護時間之前手動執行升級預先檢查。



 a| 
升級網格節點（主要管理節點）
 a| 
主管理節點會停止、升級及重新啟動。
 a| 
長達30分鐘
 a| 
您無法存取主要管理節點。系統會報告連線錯誤、您可以忽略這些錯誤。



 a| 
升級網格節點（所有其他節點）
 a| 
所有其他網格節點上的軟體都會依照您核准節點的順序進行升級。系統中的每個節點將每次關閉一個節點數分鐘。
 a| 
每個節點15至45分鐘、設備儲存節點最需要時間

*附註：* StorageGRID 針對應用裝置節點、將自動更新至最新版本的《Sfor applianceAppliance Installer》。
 a| 
* 請勿變更網格組態。
* 請勿變更稽核層級組態。
* 請勿更新ILM組態。
* 請勿執行其他維護程序、例如修補程式、取消委任或擴充。
+
*附註：*如果您需要執行恢復程序、請聯絡技術支援部門。





 a| 
啟用功能
 a| 
新版本的新功能已啟用。
 a| 
不到5分鐘
 a| 
* 請勿變更網格組態。
* 請勿變更稽核層級組態。
* 請勿更新ILM組態。
* 請勿執行其他維護程序。




 a| 
升級資料庫
 a| 
所有儲存節點上都有Cassandra資料庫表格、這些資料表都會升級。
 a| 
小時或天、視系統中的中繼資料量而定
 a| 
在*升級資料庫*工作期間、升級後的網格將正常運作、但升級仍在進行中。在此工作期間、您可以：

* 使用新StorageGRID 版的更新功能。
* 變更稽核層級組態。
* 更新ILM組態。
* 套用修補程式。
* 恢復節點。


*注意：*完成*最終升級步驟*之前、您無法執行取消委任或擴充程序。



 a| 
最終升級步驟
 a| 
移除暫用檔案、並完成新版本的升級。
 a| 
5分鐘
 a| 
當*最終升級步驟*工作完成時、您可以執行所有的維護程序。

|===
.步驟
. 預估升級所有網格節點所需的時間（考慮所有升級工作、*升級資料庫*除外）。
+
.. 將您的整個系統中的節點數乘以StorageGRID 30分鐘/節點（平均）。
.. 請在此時間加上1小時、以說明下載所需的時間 `.upgrade` 檔案、執行預先檢查驗證、並完成最終的升級步驟。


. 如果您有Linux節點、請為每個節點新增15分鐘、以說明下載及安裝RPM或Deb套件所需的時間。
. 預估升級資料庫所需的時間。
+
.. 從Grid Manager中選取*節點*。
.. 選取樹狀結構中的第一個項目（整個網格）、然後選取「* Storage*」（*儲存設備*）索引標籤。
.. 將游標暫留在*使用的儲存設備-物件中繼資料*圖表上、然後找出*使用*值、該值表示您的網格上有多少位元組的物件中繼資料。
.. 將*已用*值除以1.5 TB/天、以決定升級資料庫所需的天數。


. 新增步驟1、2和3的結果、計算升級的預估總時間。




== 範例：預估從StorageGRID 示例11.4升級到11.5的時間

假設您的系統有14個網格節點、其中8個是Linux節點。此外、假設物件中繼資料的*已用*值為6 TB。

. 將每個節點的14乘以30分鐘、再加上1小時。升級所有節點的預估時間為8小時。
. 每個節點多個8到15分鐘、以說明在Linux節點上安裝RPM或Deb套件的時間。此步驟的預估時間為2小時。
. 將6除以1.5 TB/天。「*升級資料庫*」工作的預估天數為4天。
+

NOTE: 當*升級資料庫*工作正在執行時、您可以安全地使用新功能、套用即時修復程式、以及執行節點還原作業。

. 將這些值加在一起。您應該有5天的時間完成系統升級StorageGRID 至版本11.5.0。

