---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 您必須瞭StorageGRID 解升級過程中、您的不知道哪些系統會受到影響。 
---
= 系統在升級期間的影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須瞭StorageGRID 解升級過程中、您的不知道哪些系統會受到影響。



== 不中斷升級StorageGRID

整個升級過程中、這個系統可以從用戶端應用程式擷取及擷取資料。StorageGRID網格節點在升級期間一次關閉一個節點、因此並非所有網格節點都無法使用。

若要持續提供可用度、您必須使用適當的ILM原則、確保以冗餘方式儲存物件。您也必須確保所有外部S3或Swift用戶端均設定為傳送要求至下列其中一項：

* 將此端點設定為高可用度（HA）群組StorageGRID
* 高可用度協力廠商負載平衡器
* 每個用戶端有多個閘道節點
* 每個用戶端有多個儲存節點




== 應用裝置韌體已升級

在升級過程中StorageGRID ：

* 所有StorageGRID 的VMware應用裝置節點都會自動升級至StorageGRID VMware應用程式安裝程式韌體版本3.5。
* SG6060和SGF6024應用裝置會自動升級至BIOS韌體版本3B03.EX和BMC韌體版本BMC 3.90.07。
* SG100和SG1000應用裝置會自動升級至BIOS韌體版本3B08.EC和BMC韌體版本4.64.07。




== 可能會觸發警示

當服務啟動和停止時、StorageGRID 以及當作業系統以混合版本環境運作時、可能會觸發警示（部分網格節點執行較早版本、而其他節點則已升級至較新版本）。例如、當服務停止時、您可能會看到*無法與node*通訊警示、或者當某些節點已升級StorageGRID 至BIOS 11.5、但其他節點仍在執行StorageGRID 此功能時、您可能會看到* Cassandra通訊錯誤*警示。

一般而言、這些警示會在升級完成時清除。

升級完成後、您可以從Grid Manager儀表板選取*最近解決的警示*、以檢閱任何與升級相關的警示。


NOTE: 在升級StorageGRID 至S不明11.5期間、當儲存節點停止時、可能會觸發*無法實現的ILM放置*警示。升級成功完成後、此警示可能會持續1天。



== 會產生許多SNMP通知

請注意、當網格節點在升級期間停止並重新啟動時、可能會產生大量的SNMP通知。若要避免過多通知、請取消選取*啟用SNMP代理程式通知*核取方塊（*組態*>*監控*>* SNMP代理程式*）、以在開始升級之前停用SNMP通知。然後在升級完成後重新啟用通知。



== 組態變更受到限制

在*啟用新功能*工作完成之前：

* 請勿變更任何網格組態。
* 請勿變更稽核層級組態。
* 請勿啟用或停用任何新功能。
* 請勿更新ILM組態。否則、您可能會遇到不一致且非預期的ILM行為。
* 請勿套用修補程式或恢復網格節點。


直到*最終升級步驟*工作完成為止：

* 請勿執行擴充程序。
* 請勿執行取消委任程序。

