---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: new features, 11.5, object lock, kmip, kms, ilm, decommission, node clone 
summary: 支援S3物件鎖定、支援KMIP資料加密、ILM的使用性改善、重新設計的租戶管理程式使用者介面、支援汰換某個站台、以及應用裝置節點複製程序StorageGRID StorageGRID 。 
---
= 更新功能StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
支援S3物件鎖定、支援KMIP資料加密、ILM的使用性改善、重新設計的租戶管理程式使用者介面、支援汰換某個站台、以及應用裝置節點複製程序StorageGRID StorageGRID 。



== S3物件鎖定以取得相容的資料

S3物件鎖定功能在StorageGRID 物件保護解決方案中、相當於Amazon Simple Storage Service（Amazon S3）中的S3物件鎖定。您可以啟用StorageGRID 整個S3物件鎖定功能、讓S3租戶帳戶在啟用S3物件鎖定的情況下建立貯體。然後租戶可以使用S3用戶端應用程式、選擇性地為這些儲存區中的物件指定保留和合法保留設定。

S3物件鎖定可讓租戶使用者遵守規定、規定某些物件必須保留固定時間或無限期保留。

.深入瞭解
* link:../ilm/index.html["使用ILM管理物件"]
* link:../s3/index.html["使用S3"]
* link:../tenant/index.html["使用租戶帳戶"]




== kms加密金鑰管理

您現在可以在Grid Manager中設定一或多個外部金鑰管理伺服器（KMS）、為StorageGRID 各項服務和儲存設備提供加密金鑰。每個KMS或KMS叢集都會使用金鑰管理互通性傳輸協定（KMIP）、為相關StorageGRID 聯的站台上的應用裝置節點提供加密金鑰。設備磁碟區加密之後、除非節點可以與KMS通訊、否則您無法存取應用裝置上的任何資料。


NOTE: 如果您想要使用加密金鑰管理、則必須先使用StorageGRID 「支援中心安裝程式」來啟用應用裝置的「*節點加密*」設定、然後再將應用裝置新增至網格。

.深入瞭解
* link:../admin/index.html["管理StorageGRID"]




== 資訊生命週期管理（ILM）的可用性增強功能

* 您現在可以檢視儲存資源池的總容量、包括已使用量和可用空間。您也可以查看儲存資源池中包含哪些節點、以及使用儲存資源池的ILM規則和刪除編碼設定檔。
* 您現在可以設計適用於多個租戶帳戶的ILM規則。
* 當您建立ILM規則進行銷毀編碼時、系統會提醒您將物件大小（MB）進階篩選器設定為大於0.2、以確保極小的物件不會以銷毀編碼。
* ILM原則介面現在可確保預設ILM規則永遠用於任何不符合其他規則的物件。從還原11.5開始StorageGRID 、預設規則無法使用任何基本或進階篩選器、而且會自動做為原則的最後一項規則。
+

NOTE: 如果您目前的ILM原則不符合新的要求、您可以在升級StorageGRID 至版本化至版本化版本的版本時繼續使用。不過、如果您在升級後嘗試複製不符合的原則、系統會提示您選取不含篩選器的預設規則、而且您必須將預設規則置於原則結尾。

* 當您建立新的ILM規則或新的「刪除編碼」設定檔時、預設不會再選取「所有儲存節點」儲存資源池。此外、您現在可以移除所有儲存節點儲存資源池、只要該儲存資源池未用於任何規則即可。
+

NOTE: 不建議使用All Storage Node儲存資源池、因為此儲存資源池包含所有站台。如果您將此儲存資源池與StorageGRID 包含多個站台的作業系統搭配使用、則物件的多個複本可能會放在同一個站台上。

* 您現在可以移除常用的「建立2份複本」規則（使用「所有儲存節點」儲存資源池）、只要該規則未在作用中或建議的原則中使用即可。
* 儲存在雲端儲存資源池中的物件現在可以立即刪除（同步刪除）。


.深入瞭解
* link:../ilm/index.html["使用ILM管理物件"]




== Grid Manager增強功能

* 重新設計的「租戶帳戶」頁面可讓您更輕鬆地檢視租戶帳戶使用量。租戶摘要表格現在包含「已使用空間」、「配額使用率」、「配額」及「物件數」等欄。新的*檢視詳細資料*按鈕可存取每個租戶的總覽、以及帳戶S3時段或Swift容器的詳細資料。此外、您現在可以匯出兩個 `.csv` 租戶使用情況檔案：其中一個包含所有租戶的使用值、另一個包含租戶桶或容器的詳細資料。
+
與此變更相關、我們新增了三個Prometheus新指標來追蹤租戶帳戶使用量：

+
** `storagegrid_tenant_usage_data_bytes`
** `storagegrid_tenant_usage_object_count`
** `storagegrid_tenant_usage_quota_bytes`


* 「管理群組」頁面（*組態*>*存取控制*）上的新「*存取模式*」欄位可讓您指定群組的管理權限為讀寫（預設）或唯讀。屬於具有讀寫存取模式之群組的使用者、可以在Grid Manager和Grid Management API中變更設定並執行作業。屬於具有唯讀存取模式之群組的使用者、只能檢視為群組選取的設定和功能。
+

NOTE: 當您升級StorageGRID 至支援物件11.5時、所有現有的管理群組都會選擇讀寫存取模式選項。

* 重新設計了這個使用者介面AutoSupport 。您現在可以從AutoSupport Grid Manager的單一頁面、設定事件觸發、使用者觸發和每週的動態訊息。您也可以設定AutoSupport 其他目的地以接收資訊。
+

NOTE: 如果AutoSupport 尚未啟用此功能、則Grid Manager儀表板上會出現提醒訊息。

* 在節點頁面上檢視*已用儲存設備-物件資料*圖表時、您現在可以看到網格、站台或儲存節點（*節點*>**網格/站台/儲存節點*>* Storage *）上的複寫物件資料量與銷毀編碼資料量預估值。
* 網格管理器功能表選項已重新組織、以便更容易找到選項。例如、*組態*功能表新增了*網路設定*子功能表、而*維護*和*支援*功能表中的選項現在會以字母順序列出。


.深入瞭解
* link:../admin/index.html["管理StorageGRID"]




== 租戶管理程式的增強功能

* 租戶管理程式使用者介面的外觀與組織經過徹底重新設計、以改善使用者體驗。
* 全新的租戶管理程式儀表板提供每個帳戶的高層摘要：提供庫存箱詳細資料、並顯示庫位或容器、群組、使用者及平台服務端點的數量（若已設定）。


.深入瞭解
* link:../tenant/index.html["使用租戶帳戶"]




== Prometheus計量匯出的用戶端憑證

您現在可以上傳或產生用戶端憑證（*組態*>*存取控制*>*用戶端憑證*）、以提供StorageGRID 安全、驗證的方式存取功能至《The S還原Prometheus資料庫》。例如、如果您需要使用StorageGRID Grafana從外部監控、可以使用用戶端憑證。

.深入瞭解
* link:../admin/index.html["管理StorageGRID"]




== 負載平衡器增強功能

* 在站台處理路由要求時、負載平衡器服務現在會執行負載感知路由：它會考量同一個站台上儲存節點的CPU可用度。在某些情況下、CPU可用度的相關資訊僅限於負載平衡器服務所在的站台。
+

NOTE: 在站台上至少三分之二的儲存節點升級StorageGRID 至支援版（英文）11.5並報告CPU統計資料之前、CPU認知功能將不會啟用。

* 為了增加安全性、您現在可以為每個負載平衡器端點指定一個繫結模式。端點固定功能可讓您將每個端點的存取權限限制在特定的高可用度群組或節點介面上。


.深入瞭解
* link:../admin/index.html["管理StorageGRID"]




== 物件中繼資料變更

* *新的實際保留空間指標*：為了協助您瞭解及監控每個儲存節點上的物件中繼資料空間使用量、新的Prometheus指標會顯示在儲存節點的「使用的儲存設備-物件中繼資料」圖表（*節點*>*儲存節點_*>* Storage *）上。
+
[listing]
----
storagegrid_storage_utilization_metadata_reserved
----
+
*實際保留空間*指標指出StorageGRID 、針對特定儲存節點上的物件中繼資料、保留多少空間。

* *使用大型儲存節點安裝時、中繼資料空間會增加*：StorageGRID 系統範圍的中繼資料保留空間設定已針對含有128 GB以上RAM之儲存節點的各種系統進行增加、如下所示：
+
** * 8 TB用於新安裝*：如果您要安裝新StorageGRID 的一套版本、且網格中的每個儲存節點都有128 GB以上的RAM、則系統範圍的中繼資料保留空間設定現在會設為8 TB、而非3 TB。
** * 4 TB用於升級*：如果您要升級StorageGRID 至5.2、且任何一個站台的每個儲存節點都有128 GB以上的RAM、則系統範圍的中繼資料保留空間設定現在設定為4 TB、而非3 TB。
+
「中繼資料保留空間」設定的新值可增加這些較大儲存節點的允許中繼資料空間、最高可達2.64 TB、並確保保留足夠的中繼資料空間供未來的硬體和軟體版本使用。

+
[NOTE]
====
如果您的儲存節點有足夠的RAM和磁碟區0的足夠空間、您可以在升級後手動將中繼資料保留空間設定增加至8 TB。升級完支援的更新版本更新後、保留額外的中繼資料空間StorageGRID 、將可簡化未來的硬體與軟體升級。

link:increasing-metadata-reserved-space-setting.html["增加中繼資料保留空間設定"]

====
+

NOTE: 如果StorageGRID 您的系統在任何儲存節點上儲存（或預期會儲存）超過2.64 TB的中繼資料、在某些情況下、允許的中繼資料空間會增加。如果您的儲存節點在儲存磁碟區0和超過128 GB的RAM上各有可用空間、請聯絡您的NetApp客戶代表。NetApp將審查您的需求、並盡可能增加每個儲存節點的中繼資料空間。



* *自動清除刪除的中繼資料*：儲存節點上儲存的20%以上中繼資料已準備好移除（因為已刪除對應的物件）StorageGRID 時、現在可以在該儲存節點上執行自動壓縮。此背景程序只有在系統負載低時才會執行、也就是當有可用的CPU、磁碟空間和記憶體時。新的壓縮程序會比舊版更快移除刪除物件的中繼資料、並有助於釋出空間以供儲存新物件。


.深入瞭解
* link:../admin/index.html["管理StorageGRID"]




== S3 REST API支援變更

* 您現在可以使用S3 REST API來指定 <<S3物件鎖定以取得相容的資料,S3物件鎖定>> 設定：
+
** 若要建立啟用S3物件鎖定的儲存區、請使用的「置入儲存區」要求 `x-amz-bucket-object-lock-enabled` 標頭。
** 若要判斷是否已針對某個儲存區啟用S3物件鎖定、請使用「Get Object Lock Configuration（取得物件鎖定組態）」要求。
** 將物件版本新增至啟用S3物件鎖定的儲存區時、請使用下列要求標頭來指定保留和合法保留設定： `x-amz-object-lock-mode`、 `x-amz-object-lock-retain-until-date`和 `x-amz-object-lock-legal-hold`。


* 您現在可以在版本控制的儲存區上使用刪除多個物件。
* 您現在可以使用Put、Get和Delete Bucket加密要求來管理現有S3儲存區的加密。
* 對的欄位名稱進行了少許變更 `Expiration` 參數。如果生命週期組態中的到期規則適用於特定物件、則此參數會包含在「放置物件」、「物件標頭」或「取得物件」要求的回應中。此欄位會指出先前已命名的到期規則 `rule_id`。此欄位已重新命名為 `rule-id` 以符合AWS實作。
* 根據預設、S3「Get Storage使用量」要求現在會嘗試使用強大的全域一致性來擷取租戶帳戶及其儲存區所使用的儲存設備。如果無法達到強大的全球一致性、StorageGRID 則嘗試使用強大的站台一致性來擷取使用資訊。
* 。 `Content-MD5` 現在已正確支援要求標頭。


.深入瞭解
* link:../s3/index.html["使用S3"]




== CloudMirror物件的最大大小增加至5 TB

CloudMirror複寫服務可複寫至目的地儲存區的物件大小上限增加至5 TB、StorageGRID 這是支援的最大物件大小。

.深入瞭解
* link:../s3/index.html["使用S3"]
* link:../swift/index.html["使用Swift"]




== 新增警示

針對下列功能新增了StorageGRID 適用於下列的更新警示：

* 應用裝置BMC通訊錯誤
* 偵測到應用裝置光纖通道故障
* 應用裝置Fibre Channel HBA連接埠故障
* 設備LACP連接埠遺失
* Cassandra自動執行元件錯誤
* Cassandra自動執行元件度量資料已過期
* Cassandra相容性過載
* 磁碟I/O非常緩慢
* KMS CA憑證過期
* KMS用戶端憑證過期
* 無法載入kms組態
* KMS連線錯誤
* 找不到kms加密金鑰名稱
* KMS加密金鑰旋轉失敗
* 未設定公里
* KMS金鑰無法解密應用裝置磁碟區
* KMS伺服器憑證過期
* 儲存資源池可用空間不足
* 節點網路接收框架錯誤
* 服務應用裝置儲存連線能力降級
* 儲存應用裝置儲存設備連線能力降級（先前稱為「設備儲存設備連線能力降級」）
* 租戶配額使用量高
* 非預期的節點重新開機


.深入瞭解
* link:../monitor/index.html["監控安培；疑難排解"]




== TCP支援SNMP設陷

您現在可以選取傳輸控制傳輸協定（TCP）作為SNMP設陷目的地的傳輸協定。先前只支援使用者資料包傳輸協定（UDP）傳輸協定。

.深入瞭解
* link:../monitor/index.html["監控安培；疑難排解"]




== 安裝與網路增強功能

* * MAC位址複製*：您現在可以使用MAC位址複製來增強特定環境的安全性。Mac位址複製可讓您將專用虛擬NIC用於Grid Network、管理網路及用戶端網路。讓Docker容器使用主機上專用NIC的MAC位址、可避免使用雜亂模式網路組態。在Linux型（裸機）節點的節點組態檔中新增三個新的MAC位址複製金鑰。
* *自動探索DNS和NTP主機路由*：先前、NTP和DNS伺服器必須連線的網路受到限制、例如用戶端網路上無法擁有所有NTP和DNS伺服器的需求。現在、這些限制已移除。


.深入瞭解
* link:../rhel/index.html["安裝Red Hat Enterprise Linux或CentOS"]
* link:../ubuntu/index.html["安裝Ubuntu或DEBIAN"]




== 支援在儲存節點擴充之後、重新平衡銷毀編碼（EC）資料

EC重新平衡程序是新增儲存節點之後可能需要的新命令列指令碼。當您執行此程序時、StorageGRID 將以銷毀編碼的片段重新散佈到站台上現有和新擴充的儲存節點。


IMPORTANT: 您只能在有限的情況下執行EC重新平衡程序。例如、如果您無法在擴充中新增建議數量的儲存節點、您可以使用EC重新平衡程序來儲存其他以銷毀編碼的物件。

.深入瞭解
* link:../expand/index.html["擴充網格"]




== 全新及修訂的維護程序

* *站台取消委任*：您現在可以從StorageGRID 您的作業系統中移除作業站台。連線站台取消委任程序會移除作業站台並保留資料。全新的取消委任網站精靈會引導您完成整個程序（*維護*>*取消委任*>*取消委任網站*）。
* *應用裝置節點複製*：您現在可以複製現有的應用裝置節點、將節點升級至新的應用裝置模式。例如、您可以將容量較小的應用裝置節點複製到容量較大的應用裝置。您也可以複製應用裝置節點來實作新功能、例如KMS加密所需的新*節點加密*設定。
* *能夠變更資源配置通關密碼*：您現在可以變更資源配置通關密碼（*組態*>*存取控制*>*網格密碼*）。恢復、擴充和維護程序需要通關密碼。
* *增強的SSH密碼行為*：為了加強StorageGRID 各項功能的安全性、當您將應用裝置置於維護模式時、SSH密碼將不再變更。此外、當您將節點升級StorageGRID 至Windows 11.5時、也會產生新的SSH主機憑證和主機金鑰。
+

NOTE: 如果您在升級StorageGRID 至VMware 11．5之後使用SSH登入節點、您將會收到主機金鑰已變更的警告。這是預期的行為、您可以安全地核准新金鑰。



.深入瞭解
* link:../maintain/index.html["維護"]




== 變更功能StorageGRID

* *直接存取SANtricity 適用於儲存應用設備的《支援功能》*：您現在可以SANtricity 從StorageGRID 《支援功能》安裝程式》和《Grid Manager》存取《E系列支援功能》使用者介面。使用這些新方法、無需SANtricity 使用應用裝置上的管理連接埠、即可存取《支援系統管理程式》。需要SANtricity 從Grid Manager存取「更新系統管理程式」的使用者、必須擁有新的Storage Appliance系統管理員權限。
* *節點加密*：StorageGRID 作為新KMS加密功能的一部分、全新的*節點加密*設定已新增至The Some Appliance Installer。如果您想要使用加密金鑰管理來保護應用裝置資料、則必須在應用裝置安裝的硬體組態階段啟用此設定。
* * UDP連接埠連線*：您現在可以測試StorageGRID 將某個應用程式的網路連線能力、例如用於外部NFS或DNS伺服器的連接埠。從《The SectionAppliance Installer》StorageGRID （《The SectionAppliance安裝程式》）中、選取*「Configure Networking」（設定網路）*>*「Port Connectivity Test（nmap）*」。
* *自動化安裝與組態*：StorageGRID 全新的Json組態上傳頁面已新增至《The Se Appliance Installer》（*進階*>*更新設備組態*）。此頁面可讓您使用一個檔案、在大型網格中設定多個應用裝置。此外 `configure-sga.py` Python指令碼已更新、以符合StorageGRID 《The》《The功能》《The》《The》《應用裝置安裝程式》》》。


.深入瞭解
* link:../sg100-1000/index.html["SG100  機；SG1000服務應用裝置"]
* link:../sg6000/index.html["SG6000儲存設備"]
* link:../sg5700/index.html["SG5700儲存設備"]
* link:../sg5600/index.html["SG5600儲存設備"]




== 稽核訊息的變更

* *自動清除被覆寫的物件*：在特定情況下、先前被覆寫的物件不會從磁碟移除、導致額外的空間使用量。這些使用者無法存取的覆寫物件現在會自動移除、以節省儲存空間。如需詳細資訊、請參閱LKCU稽核訊息。
* * S3物件鎖定的新稽核代碼*：SPUT稽核訊息中新增了四個新的稽核代碼以納入 <<S3物件鎖定以取得相容的資料,S3物件鎖定>> 要求標頭：
+
** LKEN：物件鎖定已啟用
** LKLH：物件鎖定合法持有
** LKMD：物件鎖定保留模式
** LKRU：物件鎖定保留直到日期


* *上次修改時間和先前物件大小的新欄位*：您現在可以追蹤物件被覆寫的時間以及原始物件大小。
+
** MME（上次修改時間）欄位已新增至下列稽核訊息：
+
*** SDEL（S3刪除）
*** SPUT（S3 PUT）
*** WDEL（Swift刪除）
*** WPUT（Swift Put）


** CSIZ（舊版物件大小）欄位已新增至OVWC（物件覆寫）稽核訊息。




.深入瞭解
* link:../audit/index.html["檢閱稽核記錄"]




== 新的NMS.requestlog檔案

新的記錄檔、 `/var/local/log/nms.requestlog`在所有管理節點上進行維護。此檔案包含從管理API傳出連線至內部StorageGRID 支援服務的相關資訊。

.深入瞭解
* link:../monitor/index.html["監控安培；疑難排解"]




== 文件變更StorageGRID

* 為了讓網路資訊和需求更容易找到、並說明資訊也適用於StorageGRID VMware應用裝置節點、網路文件已從軟體安裝指南（RedHat Enterprise Linux/CentOS、Ubuntu / DEBIANE和VMware）移至新的網路指南。
+
link:../network/index.html["網路準則"]

* 為了讓ILM相關的指示和範例更容易找到、使用資訊生命週期管理來管理物件的文件已從_管理員指南_移至新的ILM指南。
+
link:../ilm/index.html["使用ILM管理物件"]

* 全新FabricPool 的《支援功能》指南概述如何將StorageGRID 「支援功能」設定為NetApp FabricPool 的支援功能、並說明最佳實務做法、以設定ILM和其他StorageGRID 支援FabricPool 功能來支援功能。
+
link:../fabricpool/index.html["設定StorageGRID 適用於FabricPool 靜態的"]

* 您現在可以從Grid Manager存取多段教學影片。目前的影片提供管理警示、自訂警示、ILM規則及ILM原則的指示。

