---
permalink: network/networking-and-ports-for-platform-services-and-cloud-storage-pools.html 
sidebar: sidebar 
keywords:  
summary: 如果您計畫使用StorageGRID 支援不支援的平台服務或雲端儲存資源池、則必須設定網格網路和防火牆、以確保能夠到達目的地端點。平台服務包括提供搜尋整合、事件通知及CloudMirror複寫的外部服務。 
---
= 適用於平台服務和雲端儲存資源池的網路和連接埠
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您計畫使用StorageGRID 支援不支援的平台服務或雲端儲存資源池、則必須設定網格網路和防火牆、以確保能夠到達目的地端點。平台服務包括提供搜尋整合、事件通知及CloudMirror複寫的外部服務。

平台服務需要從儲存節點存取、而儲存節點則是StorageGRID 將此項目裝載到外部服務端點。提供存取的範例包括：

* 在具有ADC服務的儲存節點上、使用Aesl項目來設定唯一的管理網路、這些項目會路由傳送至目標端點。
* 仰賴用戶端網路提供的預設路由。在此範例中、不受信任的用戶端網路功能可用來限制傳入連線。


雲端儲存資源池也需要從儲存節點存取外部服務所提供的端點、例如Amazon S3 Glacier或Microsoft Azure Blob儲存設備。

根據預設、平台服務和雲端儲存資源池通訊會使用下列連接埠：

* *80*：適用於以開頭的端點URI `http`
* * 443*：適用於以開頭的端點URI `https`


建立或編輯端點時、可以指定不同的連接埠。

如果您使用不透明的Proxy伺服器、也必須設定Proxy設定、允許訊息傳送到外部端點、例如網際網路上的端點。請參閱管理StorageGRID 功能、瞭解如何設定Proxy設定。

如需不受信任用戶端網路的詳細資訊、請參閱《關於管理StorageGRID 》的說明。如需平台服務的詳細資訊、請參閱租戶帳戶使用說明。如需Cloud Storage Pool的詳細資訊、請參閱使用資訊生命週期管理來管理物件的指示。

.相關資訊
link:network-port-reference.html["網路連接埠參考"]

link:../primer/index.html["網格入門指南"]

link:../admin/index.html["管理StorageGRID"]

link:../tenant/index.html["使用租戶帳戶"]

link:../ilm/index.html["使用ILM管理物件"]
