---
permalink: tenant/what-platform-services-endpoint-is.html 
sidebar: sidebar 
keywords: storagegrid, tenant, platform services, platform service, platform services endpoint, platform service endpoint, endpoint 
summary: 當您建立平台服務端點時、請指定StorageGRID 存取外部目的地所需的資訊。 
---
= 什麼是平台服務端點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您建立平台服務端點時、請指定StorageGRID 存取外部目的地所需的資訊。

例如、如果您想要將物件從StorageGRID 某個物件庫複寫到S3庫位、您可以建立一個平台服務端點、其中包含StorageGRID 資訊和認證、供您存取AWS上的目的地庫位所需的資訊和認證資料。

每種類型的平台服務都需要自己的端點、因此您必須為每個打算使用的平台服務至少設定一個端點。在定義平台服務端點之後、您可以在用來啟用服務的組態XML中、使用端點的URN作為目的地。

您可以將同一個端點作為多個來源儲存區的目的地。例如、您可以設定多個來源儲存區、將物件中繼資料傳送至同一個搜尋整合端點、以便在多個儲存區之間執行搜尋。您也可以將來源儲存區設定為使用多個端點做為目標、以便將有關物件建立的通知傳送至單一SNS主題、並將物件刪除的通知傳送至第二個SNS主題。



== 用於CloudMirror複寫的端點

支援代表S3儲存區的複寫端點。StorageGRID這些儲存庫可能託管在Amazon Web Services、相同或遠端StorageGRID 的功能或其他服務上。



== 通知的端點

支援Simple Notification Service（SNS）端點。StorageGRID不支援簡單佇列服務（SQS）或AWS Lambda端點。



== 搜尋整合服務的端點

支援代表Elasticsearch叢集的搜尋整合端點。StorageGRID這些彈性搜尋叢集可位於本機資料中心、或託管於AWS雲端或其他地方。

搜尋整合端點是指特定的彈性搜尋索引和類型。您必須先在Elasticsearch中建立索引、才能在StorageGRID 其中建立端點、否則端點建立將會失敗。您不需要在建立端點之前建立類型。如果需要、當將物件中繼資料傳送至端點時、將會建立類型。StorageGRID

.相關資訊
link:../admin/index.html["管理StorageGRID"]
