---
permalink: vmware/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: storagegrid, vmware, download installation files, downloading installation files 
summary: 您必須下載StorageGRID 更新安裝歸檔並擷取檔案。 
---
= 下載及解壓縮StorageGRID 安裝文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須下載StorageGRID 更新檔、並擷取檔案。

.步驟
. 請前往NetApp下載頁StorageGRID 面以瞭解決此問題。
+
https://["NetApp下載StorageGRID"^]

. 選取下載最新版本的按鈕、或從下拉式功能表中選取其他版本、然後選取*執行*。
. 以您NetApp帳戶的使用者名稱和密碼登入。
. 如果出現Caution/MustRead說明、請閱讀並勾選核取方塊。
+
安裝StorageGRID 完此版本的更新後、您必須套用所有必要的修補程式。如需詳細資訊、請參閱還原與維護指示中的修復程序程序。

. 閱讀使用者授權合約、勾選核取方塊、然後選取*接受並繼續*。
. 在*安裝StorageGRID S編*欄中、選取適當的軟體。
+
下載 `.tgz` 或 `.zip` 為您的平台歸檔檔案。

+
** `StorageGRID-Webscale-version-VMware-uniqueID.zip`
** `StorageGRID-Webscale-version-VMware-uniqueID.tgz`





NOTE: 使用 `.zip` 檔案（如果您是在服務筆記型電腦上執行Windows）。

. 儲存並擷取歸檔檔案。
. 從下列清單中選擇您需要的檔案。
+
您需要的檔案取決於您規劃的網格拓撲、以及如何部署StorageGRID 您的作業系統。




NOTE: 表中列出的路徑是相對於擷取安裝歸檔所安裝的最上層目錄。

[cols="1a,1a"]
|===
| 路徑和檔案名稱 | 說明 


| /vSphere/README  a| 
說明StorageGRID 包含在更新檔中的所有檔案的文字檔。



| ./vSphere/NLF000000.txt  a| 
不提供產品任何支援權利的免費授權。



| /vSphere/NetApp-SG-version -SHA-vmdk  a| 
用來做為建立網格節點虛擬機器範本的虛擬機器磁碟檔案。



| /vSphere/vSphere-primer-admin.OVF ./vSphere/vSphere-prime-admin.mf  a| 
開放式虛擬化格式範本檔案 (`.ovf`）和資訊清單檔案 (`.mf`）以部署主管理節點。



| /vSphere/vSphere-non-prime-admin.OVF ./vSphere/vSphere-non-prime-admin.mf  a| 
範本檔案 (`.ovf`）和資訊清單檔案 (`.mf`）以部署非主要管理節點。



| /vSphere/vSphere-archive .OVF ./vSphere/vSphere-archive、mf  a| 
範本檔案 (`.ovf`）和資訊清單檔案 (`.mf`）以部署歸檔節點。



| /vSphere/vSphere-gateway.OVF ./vSphere/vSphere-gateway.mf  a| 
範本檔案 (`.ovf`）和資訊清單檔案 (`.mf`）以部署閘道節點。



| /vSphere/vSphere-storage。OVF ./vSphere/vSphere-storage  a| 
範本檔案 (`.ovf`）和資訊清單檔案 (`.mf`）以部署虛擬機器型儲存節點。



| 部署指令碼工具 | 說明 


| ./vSphere/deploy-vsphere-ovftool.sh  a| 
Bash Shell指令碼、用於自動化虛擬網格節點的部署。



| ./vSphere/deploy-vsphere-ovftool-sample.ini  a| 
與搭配使用的範例組態檔 `deploy-vsphere-ovftool.sh` 指令碼：



| ./vSphere/configure-storagegrid.py  a| 
Python指令碼、用於自動化StorageGRID 組態的功能。



| ./vSphere/configure-sga.py  a| 
Python指令碼、用於自動化StorageGRID 設定不必要的應用程式。



| ./vSphere/storagegrid-ssoauth.py  a| 
啟用單一登入時、您可用來登入Grid Management API的Python指令碼範例。



| /vSphere/configure-storagegrid、same.json  a| 
與搭配使用的範例組態檔 `configure-storagegrid.py` 指令碼：



| /vSphere/configure-storagegrid、blank.json  a| 
與搭配使用的空白組態檔 `configure-storagegrid.py` 指令碼：

|===
.相關資訊
link:../maintain/index.html["維護"]
