---
permalink: admin/configuring-custom-server-certificate-for-storage-node-or-clb.html 
sidebar: sidebar 
keywords:  
summary: 您可以取代用於S3或Swift用戶端連線至儲存節點或閘道節點上CLB服務（已過時）的伺服器憑證。置換的自訂伺服器憑證是您組織專屬的。 
---
= 設定自訂伺服器憑證、以連線至儲存節點或CLB服務
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以取代用於S3或Swift用戶端連線至儲存節點或閘道節點上CLB服務（已過時）的伺服器憑證。置換的自訂伺服器憑證是您組織專屬的。

.關於這項工作
根據預設、每個儲存節點都會核發由網格CA簽署的X．509伺服器憑證。這些CA簽署的憑證可由單一通用的自訂伺服器憑證和對應的私密金鑰取代。

所有儲存節點都使用單一自訂伺服器憑證、因此如果用戶端在連線至儲存端點時需要驗證主機名稱、則必須將憑證指定為萬用字元或多網域憑證。定義自訂憑證、使其符合網格中的所有儲存節點。

在伺服器上完成組態之後、使用者可能還需要在S3或Swift API用戶端上安裝根CA憑證、以供存取系統、視您使用的根憑證授權單位（CA）而定。


NOTE: 為了確保作業不會因為失敗的伺服器憑證而中斷、當根伺服器憑證即將過期時、會觸發* Storage API端點的伺服器憑證過期*警示和舊版Storage API服務端點憑證過期（SCEP）警示。如有必要、您可以選取*支援**工具* Grid拓撲*、以檢視目前服務憑證過期的天數。然後選取「*主要管理節點_* CMN* Resources *」。

只有在用戶端使用StorageGRID 閘道節點上過時的CLB服務連線至功能區、或直接連線至儲存節點時、才會使用自訂憑證。使用StorageGRID 管理節點或閘道節點上的負載平衡器服務連線至支援功能的S3或Swift用戶端、會使用針對負載平衡器端點所設定的憑證。


NOTE: 負載平衡器端點認證*到期時會觸發即將到期的負載平衡器端點警示。

.步驟
. 選擇*組態*>*網路設定*>*伺服器憑證*。
. 在「物件儲存API服務端點伺服器憑證」區段中、按一下「*安裝自訂憑證*」。
. 上傳所需的伺服器憑證檔案：
+
** *伺服器憑證*：自訂伺服器憑證檔案 (`.crt`）。
** *伺服器憑證私密金鑰*：自訂伺服器憑證私密金鑰檔 (`.key`）。
+

NOTE: EC私密金鑰必須大於或等於224位元。RSA私密金鑰必須大於或等於2048位元。

** * CA產品組合*：單一檔案、包含來自每個中繼發行憑證授權單位（CA）的憑證。檔案應包含以憑證鏈順序串聯的每個由PEE編碼的CA憑證檔案。


. 按一下「 * 儲存 * 」。
+
自訂伺服器憑證會用於所有後續的新API用戶端連線。

+
選取索引標籤以顯示有關預設StorageGRID 的伺服器認證或上傳的CA簽署認證的詳細資訊。

+

NOTE: 上傳新的憑證後、請允許清除任何相關的憑證過期警示（或舊版警示）一天。

. 重新整理頁面以確保網頁瀏覽器已更新。


.相關資訊
link:../s3/index.html["使用S3"]

link:../swift/index.html["使用Swift"]

link:configuring-s3-api-endpoint-domain-names.html["設定S3 API端點網域名稱"]
