---
permalink: admin/configuring-custom-server-certificate-for-grid-manager-tenant-manager.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用StorageGRID 單一自訂伺服器憑證來取代預設的支援伺服器憑證、讓使用者能夠存取Grid Manager和租戶管理程式、而不會遇到安全性警告。 
---
= 為Grid Manager和Tenant Manager設定自訂伺服器憑證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用StorageGRID 單一自訂伺服器憑證來取代預設的支援伺服器憑證、讓使用者能夠存取Grid Manager和租戶管理程式、而不會遇到安全性警告。

.關於這項工作
根據預設、每個管理節點都會核發由網格CA簽署的憑證。這些CA簽署的憑證可由單一通用的自訂伺服器憑證和對應的私密金鑰取代。

由於所有管理節點都使用單一自訂伺服器憑證、因此如果用戶端在連線至Grid Manager和Tenant Manager時需要驗證主機名稱、則必須將憑證指定為萬用字元或多網域憑證。定義自訂憑證、使其符合網格中的所有管理節點。

您需要在伺服器上完成組態、視您使用的根憑證授權單位（CA）而定、使用者可能也需要在網頁瀏覽器中安裝根CA憑證、以便存取Grid Manager和租戶管理程式。


NOTE: 為了確保作業不會因為伺服器憑證故障而中斷、當此伺服器憑證即將過期時、會觸發* Management Interface*警示伺服器憑證過期、以及舊版管理介面憑證過期（MCEP）警示。如有需要、您可以選取*支援*>*工具*>*網格拓撲*、以檢視目前服務憑證過期的天數。然後選取「*主管理節點_*>* CMN*>*資源*」。

[NOTE]
====
如果您使用網域名稱而非IP位址來存取Grid Manager或Tenant Manager、則瀏覽器會顯示憑證錯誤、且在發生下列任一情況時、不會出現跳過的選項：

* 您的自訂管理介面伺服器憑證將過期。
* 您可以從自訂管理介面伺服器憑證還原為預設的伺服器憑證。


====
.步驟
. 選擇*組態*>*網路設定*>*伺服器憑證*。
. 在「管理介面伺服器憑證」區段中、按一下「*安裝自訂憑證*」。
. 上傳所需的伺服器憑證檔案：
+
** *伺服器憑證*：自訂伺服器憑證檔案 (`.crt`）。
** *伺服器憑證私密金鑰*：自訂伺服器憑證私密金鑰檔 (`.key`）。
+

NOTE: EC私密金鑰必須大於或等於224位元。RSA私密金鑰必須大於或等於2048位元。

** * CA產品組合*：單一檔案、包含來自每個中繼發行憑證授權單位（CA）的憑證。檔案應包含以憑證鏈順序串聯的每個由PEE編碼的CA憑證檔案。


. 按一下「 * 儲存 * 」。
+
自訂伺服器憑證會用於所有後續的新用戶端連線。

+
選取索引標籤以顯示有關預設StorageGRID 的伺服器認證或上傳的CA簽署認證的詳細資訊。

+

NOTE: 上傳新的憑證後、請允許清除任何相關的憑證過期警示（或舊版警示）一天。

. 重新整理頁面以確保網頁瀏覽器已更新。

