---
permalink: admin/creating-tenant-account-if-sso-is-enabled.html 
sidebar: sidebar 
keywords:  
summary: 當您建立租戶帳戶時、可以指定名稱、用戶端傳輸協定及儲存配額（選用）。如果啟用單一登入（SSO）以StorageGRID 供執行功能、您也可以指定哪個聯盟群組具有root存取權限來設定租戶帳戶。 
---
= 如果啟用SSO、請建立租戶帳戶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您建立租戶帳戶時、可以指定名稱、用戶端傳輸協定及儲存配額（選用）。如果啟用StorageGRID 單一登入（SSO）來執行功能、您也可以指定哪個聯盟群組具有root存取權限來設定租戶帳戶。

.步驟
. 在*顯示名稱*文字方塊中、輸入此租戶帳戶的顯示名稱。
+
顯示名稱不一定是唯一的。建立租戶帳戶時、會收到唯一的數字帳戶ID。

. 選擇此租戶帳戶將使用的用戶端傳輸協定、例如* S37*或* Swift。
. 對於S3租戶帳戶、除非您不想讓此租戶使用平台服務做為S3貯體、否則請保留「*允許平台服務*」核取方塊。
+
如果已啟用平台服務、租戶可以使用諸如CloudMirror複寫等功能來存取外部服務。您可能想要停用這些功能、以限制租戶使用的網路頻寬或其他資源量。請參閱「老舊平台服務」。

. 在「*儲存配額*」文字方塊中、選擇性地輸入您要讓此租戶物件使用的GB、TB或PB的最大數量。然後從下拉式清單中選取單位。
+
如果您希望此租戶擁有無限配額、請將此欄位留白。

+

NOTE: 租戶的儲存配額代表邏輯容量（物件大小）、而非實體容量（磁碟大小）。ILM複本和銷毀編碼不會影響使用的配額量。如果超過配額、租戶帳戶就無法建立新物件。

+

NOTE: 若要監控每個租戶帳戶的儲存使用量、請選取*使用量*。租戶帳戶也可以從租戶管理程式的儀表板或租戶管理API監控自己的儲存使用量。請注意、如果節點與網格中的其他節點隔離、租戶的儲存使用量值可能會過期。當網路連線恢復時、總計將會更新。

. 請注意、「*使用自己的身分識別來源*」核取方塊會取消核取並停用。
+
由於啟用SSO、租戶必須使用為Grid Manager設定的身分識別來源。沒有本機使用者可以登入。

. 在*根存取群組*欄位中、從Grid Manager選取現有的聯盟群組、以取得租戶的初始根存取權限。
+

NOTE: 如果您有足夠的權限、則當您按一下欄位時、會列出Grid Manager中現有的聯盟群組。否則、請輸入群組的唯一名稱。

. 按一下「 * 儲存 * 」。
+
隨即建立租戶帳戶。此時會出現「租戶帳戶」頁面、其中包含新租戶的一列。

. 如果您是根存取群組中的使用者、可選擇按一下新租戶的*登入*連結、立即存取租戶管理程式、以便設定租戶。否則、請提供*登入*連結的URL給租戶帳戶管理員。（租戶的URL是任何管理節點的完整網域名稱或IP位址、後面接著 `/?accountId=_20-digit-account-id_`）
+

NOTE: 如果您按一下「*登入*」、但您不屬於租戶帳戶的「根存取」群組、則會顯示「拒絕存取」訊息。



.相關資訊
link:configuring-sso.html["設定單一登入"]

link:managing-platform-services-for-s3-tenant-accounts.html["管理S3租戶帳戶的平台服務"]

link:../tenant/index.html["使用租戶帳戶"]
