---
permalink: admin/managing-local-users.html 
sidebar: sidebar 
keywords:  
summary:  
---
= 管理本機使用者
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立本機使用者、並將其指派給本機管理群組、以決定這些使用者可以存取哪些Grid Manager功能。

Grid Manager包含一個預先定義的本機使用者、名為「root」。雖然您可以新增及移除本機使用者、但無法移除root使用者。


NOTE: 如果已啟用單一登入（SSO）、則本機使用者無法登入StorageGRID 到畫面。

* 您必須使用支援的瀏覽器登入Grid Manager。
* 您必須擁有特定的存取權限。




== 建立本機使用者

如果您已建立本機管理群組、則可以建立一或多個本機使用者、並將每個使用者指派給一或多個群組。群組的權限可控制使用者可以存取的Grid Manager功能。

.關於這項工作
您只能建立本機使用者、而且只能將這些使用者指派給本機管理群組。同盟使用者和同盟群組是使用外部身分識別來源進行管理。

.步驟
. 選擇*組態*>*存取控制*>*管理使用者*。
. 按一下「 * 建立 * 」。
. 輸入使用者的顯示名稱、唯一名稱和密碼。
. 將使用者指派給一或多個控制存取權限的群組。
+
群組名稱清單是從群組表格產生的。

. 按一下「 * 儲存 * 」。


.相關資訊
link:managing-admin-groups.html["管理管理群組"]



== 修改本機使用者的帳戶

您可以修改本機管理員使用者的帳戶、以更新使用者的顯示名稱或群組成員資格。您也可以暫時禁止使用者存取系統。

.關於這項工作
您只能編輯本機使用者。同盟使用者詳細資料會自動與外部身分識別來源同步。

.步驟
. 選擇*組態*>*存取控制*>*管理使用者*。
. 選取您要編輯的使用者。
+
如果您的系統包含20個以上的項目、您可以指定一次在每個頁面上顯示的列數。然後、您可以使用瀏覽器的「尋找」功能、在目前顯示的列中搜尋特定項目。

. 按一下 * 編輯 * 。
. 您也可以選擇變更名稱或群組成員資格。
. 或者、若要防止使用者暫時存取系統、請勾選*拒絕存取*。
. 按一下「 * 儲存 * 」。
+
新設定會在使用者下次登出後重新登入Grid Manager時套用。





== 刪除本機使用者的帳戶

您可以刪除不再需要存取Grid Manager的本機使用者帳戶。

.步驟
. 選擇*組態*>*存取控制*>*管理使用者*。
. 選取您要刪除的本機使用者。
+

NOTE: 您無法刪除預先定義的根本機使用者。

+
如果您的系統包含20個以上的項目、您可以指定一次在每個頁面上顯示的列數。然後、您可以使用瀏覽器的「尋找」功能、在目前顯示的列中搜尋特定項目。

. 按一下「*移除*」。
. 按一下「*確定*」。




== 變更本機使用者的密碼

本機使用者可以使用Grid Manager橫幅中的*變更密碼*選項來變更自己的密碼。此外、具有「管理使用者」頁面存取權的使用者、也可以變更其他本機使用者的密碼。

.關於這項工作
您只能變更本機使用者的密碼。同盟使用者必須在外部身分識別來源中變更自己的密碼。

.步驟
. 選擇*組態*>*存取控制*>*管理使用者*。
. 從「使用者」頁面選取使用者。
+
如果您的系統包含20個以上的項目、您可以指定一次在每個頁面上顯示的列數。然後、您可以使用瀏覽器的「尋找」功能、在目前顯示的列中搜尋特定項目。

. 按一下*變更密碼*。
. 輸入並確認密碼、然後按一下*「Save*（儲存*）」。

