---
permalink: s3/get-object.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用S3取得物件要求、從S3儲存區擷取物件。 
---
= 取得物件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用S3取得物件要求、從S3儲存區擷取物件。



== 不支援零件編號要求參數

。 `partNumber` 「取得物件要求」不支援「要求」參數。您無法執行GET要求、以擷取多個部分物件的特定部分。傳回501未實作錯誤、並顯示下列訊息：

[listing]
----
GET Object by partNumber is not implemented
----


== 使用客戶提供的加密金鑰（SSE-C）要求伺服器端加密標頭

如果物件是以您提供的唯一金鑰加密、請使用所有三個標頭。

* `x-amz-server-side-encryption-customer-algorithm`：指定 `AES256`。
* `x-amz-server-side-encryption-customer-key`：指定物件的加密金鑰。
* `x-amz-server-side-encryption-customer-key-MD5`：指定對象加密密鑰的md5摘要。



IMPORTANT: 您提供的加密金鑰永遠不會儲存。如果您遺失加密金鑰、就會遺失對應的物件。在使用客戶提供的金鑰來保護物件資料之前、請先檢閱「使用伺服器端加密」中的考量事項。



== 使用者中繼資料中的UTF-8字元

在使用者定義的中繼資料中、無法剖析或解譯轉義的utf-8字元。StorageGRID在使用者定義的中繼資料中取得轉義為UTF-8字元的物件要求、不會傳回 `x-amz-missing-meta` 如果金鑰名稱或值包含不可列印的字元、則為標頭。



== 不支援的要求標頭

不支援並傳回下列要求標頭 `XNotImplemented`：

* `x-amz-website-redirect-location`




== 版本管理

如果是 `versionId` 未指定SubResource、此作業會擷取版本控制儲存區中最新版本的物件。如果物件的目前版本是刪除標記、則會傳回「未找到」狀態 `x-amz-delete-marker` 回應標頭設定為 `true`。



== 取得雲端儲存池物件的行為

如果物件已儲存在Cloud Storage Pool中（請參閱管理物件的指示、並進行資訊生命週期管理）、則Get物件要求的行為取決於物件的狀態。如需詳細資訊、請參閱「標頭物件」。


NOTE: 如果物件儲存在雲端儲存資源池中、而且網格上也有一個或多個物件複本、則「Get Object（取得物件）」要求會先嘗試從網格擷取資料、然後再從雲端儲存資源池擷取資料。

|===
| 物件狀態 | Get物件的行為 


 a| 
物件擷取到StorageGRID 不經ILM評估、或儲存在傳統儲存資源池中的物件、或使用銷毀編碼
 a| 
`200 OK`

系統會擷取物件複本。



 a| 
Cloud Storage Pool中的物件、但尚未轉換為無法擷取的狀態
 a| 
`200 OK`

系統會擷取物件複本。



 a| 
物件移轉至無法擷取的狀態
 a| 
`403 Forbidden`、 `InvalidObjectState`

使用POST物件還原要求、將物件還原至可擷取的狀態。



 a| 
正在從無法擷取的狀態還原的物件
 a| 
`403 Forbidden`、 `InvalidObjectState`

等待POST物件還原要求完成。



 a| 
物件已完全還原至雲端儲存資源池
 a| 
`200 OK`

系統會擷取物件複本。

|===


== 雲端儲存資源池中的多部份或分段物件

如果您上傳了多個部分的物件、或StorageGRID 是將一個大型物件分割成多個區段、StorageGRID 則透過取樣物件的一部分或區段、決定該物件是否可在Cloud Storage Pool中使用。在某些情況下、可能會錯誤傳回「Get物件」要求 `200 OK` 當物件的某些部分已轉換為無法擷取的狀態、或物件的某些部分尚未還原時。

在這些情況下：

* Get Object要求可能會傳回部分資料、但會在傳輸中途停止。
* 隨後可能會傳回「Get Object」（取得物件）要求 `403 Forbidden`。


.相關資訊
link:using-server-side-encryption.html["使用伺服器端加密"]

link:../ilm/index.html["使用ILM管理物件"]

link:post-object-restore.html["POST物件還原"]

link:s3-operations-tracked-in-audit-logs.html["稽核記錄中追蹤的S3作業"]
