---
permalink: s3/operations-on-objects.html 
sidebar: sidebar 
keywords: bucket, buckets, operations on buckets 
summary: 本節說明StorageGRID 此「物件」的「物件」功能如何執行S3 REST API作業。 
---
= 物件上的作業
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本節說明StorageGRID 此「物件」的「物件」功能如何執行S3 REST API作業。

* link:using-s3-object-lock.html["使用S3物件鎖定"]
* link:using-server-side-encryption.html["使用伺服器端加密"]
* link:get-object.html["取得物件"]
* link:head-object.html["標頭物件"]
* link:post-object-restore.html["POST物件還原"]
* link:put-object.html["放置物件"]
* link:put-object-copy.html["放置物件-複製"]


下列條件適用於所有物件作業：

* 物件上的所有作業均支援不一致的控制、但下列項目除外StorageGRID ：
+
** 取得物件ACL
** `OPTIONS /`
** 將物件保留為合法
** 保留物件


* 相互衝突的用戶端要求（例如兩個寫入同一個金鑰的用戶端）會以「最新致勝」的方式解決。「最新致勝」評估的時間取決於StorageGRID VMware系統何時完成指定的要求、而非S3用戶端何時開始運作。
* 所有物件均由庫位擁有者擁有、包括匿名使用者或其他帳戶所建立的物件。StorageGRID
* 透過StorageGRID Swift擷取至整個系統的資料物件無法透過S3存取。


下表說明StorageGRID 了Ss哪些 物件是由S3 REST API物件執行。

|===
| 營運 | 實作 


 a| 
刪除物件
 a| 
多因素驗證（MFA）和回應標頭 `x-amz-mfa` 不受支援。

處理刪除物件要求時StorageGRID 、功能區會嘗試立即從所有儲存位置移除物件的所有複本。如果成功、StorageGRID 則會立即將回應傳回給用戶端。如果無法在30秒內移除所有複本（例如、因為某個位置暫時無法使用）、StorageGRID 則將複本排入佇列以供移除、然後向用戶端指出成功。

*版本管理*

若要移除特定版本、申請者必須是貯體擁有者、並使用 `versionId` 子資源：使用此子資源會永久刪除版本。如果是 `versionId` 對應於刪除標記、即回應標頭 `x-amz-delete-marker` 傳回設定為 `true`。

* 如果刪除的物件不含 `versionId` 子資源在啟用版本的儲存區上、會產生刪除標記。。 `versionId` 刪除標記會使用傳回 `x-amz-version-id` 回應標頭和 `x-amz-delete-marker` 回應標頭會傳回設定為 `true`。
* 如果刪除的物件不含 `versionId` 子資源在版本暫停的儲存區上、會永久刪除現有的'null '版本或'null '刪除標記、並產生新的'null '刪除標記。。 `x-amz-delete-marker` 回應標頭會傳回設定為 `true`。


*附註*：在某些情況下、物件可能會有多個刪除標記。



 a| 
刪除多個物件
 a| 
多因素驗證（MFA）和回應標頭 `x-amz-mfa` 不受支援。

您可以在同一個要求訊息中刪除多個物件。



 a| 
刪除物件標記
 a| 
使用 `tagging` SubResource可移除物件的所有標記。以所有Amazon S3 REST API行為來實作。

*版本管理*

如果是 `versionId` 查詢參數未在要求中指定、此作業會刪除版本控制儲存區中物件最新版本的所有標記。如果物件的目前版本是刪除標記、則會傳回「MethodNotSupported」狀態 `x-amz-delete-marker` 回應標頭設定為 `true`。



 a| 
取得物件
 a| 
link:get-object.html["取得物件"]



 a| 
取得物件ACL
 a| 
如果提供帳戶所需的存取認證資料、則作業會傳回正面回應、並傳回物件擁有者的ID、顯示名稱和權限、表示擁有者擁有物件的完整存取權。



 a| 
取得物件合法持有
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["使用S3物件鎖定"]



 a| 
取得物件保留
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["使用S3物件鎖定"]



 a| 
取得物件標記
 a| 
使用 `tagging` SubResource可傳回物件的所有標記。以所有Amazon S3 REST API行為來實作

*版本管理*

如果是 `versionId` 查詢參數未在要求中指定、此作業會傳回版本控制儲存區中物件最新版本的所有標記。如果物件的目前版本是刪除標記、則會傳回「MethodNotSupported」狀態 `x-amz-delete-marker` 回應標頭設定為 `true`。



 a| 
標頭物件
 a| 
link:head-object.html["標頭物件"]



 a| 
POST物件還原
 a| 
link:post-object-restore.html["POST物件還原"]



 a| 
放置物件
 a| 
link:put-object.html["放置物件"]



 a| 
放置物件-複製
 a| 
link:put-object-copy.html["放置物件-複製"]



 a| 
將物件保留為合法
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["使用S3物件鎖定"]



 a| 
保留物件
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["使用S3物件鎖定"]



 a| 
放置物件標記
 a| 
使用 `tagging` SubResource可將一組標記新增至現有物件。以所有Amazon S3 REST API行為來實作

*標記更新和擷取行為*

當您使用「放置物件」標記來更新物件的標記時、StorageGRID 無法重新擷取物件。這表示不會使用相符ILM規則中指定的擷取行為選項。當ILM由正常背景ILM程序重新評估時、會對更新所觸發的物件放置位置進行任何變更。

這表示、如果ILM規則使用嚴格選項來擷取行為、則無法進行所需的物件放置（例如、因為新需要的位置無法使用）、則不會採取任何行動。更新後的物件會保留其目前的放置位置、直到能夠放置所需的位置為止。

*解決衝突*

相互衝突的用戶端要求（例如兩個寫入同一個金鑰的用戶端）會以「最新致勝」的方式解決。「最新致勝」評估的時間取決於StorageGRID VMware系統何時完成指定的要求、而非S3用戶端何時開始運作。

*版本管理*

如果是 `versionId` 查詢參數未在要求中指定、該作業會將標記新增至版本控制儲存區中物件的最新版本。如果物件的目前版本是刪除標記、則會傳回「MethodNotSupported」狀態 `x-amz-delete-marker` 回應標頭設定為 `true`。

|===
.相關資訊
link:consistency-controls.html["一致性控管"]

link:s3-operations-tracked-in-audit-logs.html["稽核記錄中追蹤的S3作業"]
