---
permalink: s3/storagegrid-s3-rest-api-operations.html 
sidebar: sidebar 
keywords:  
summary:  
---
= 支援SS3 REST API作業StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 REST API上新增了特定StorageGRID 於該系統的作業。



== 取得時段一致性要求

「Get Bucket一致性」要求可讓您決定套用至特定Bucket的一致性層級。

預設的一致性控制項設定為保證新建立物件的寫入後讀取。

您必須具有S3：GetBucketConsistency權限或帳戶根權限、才能完成此作業。



=== 申請範例

[source, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-consistency HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


=== 回應

在回應XML中、 `<Consistency>` 會傳回下列其中一個值：

|===
| 一致性控制 | 說明 


 a| 
全部
 a| 
所有節點都會立即接收資料、否則要求將會失敗。



 a| 
強大的全球化技術
 a| 
保證所有站台所有用戶端要求的寫入後讀取一致性。



 a| 
強式網站
 a| 
保證站台內所有用戶端要求的寫入後讀取一致性。



 a| 
全新寫入後讀取
 a| 
（預設）為新物件提供寫入後讀取一致性、並最終確保物件更新一致。提供高可用度與資料保護保證。符合Amazon S3一致性保證。

*附註：*如果您的應用程式在不存在的物件上使用標頭要求、如果一個或多個儲存節點無法使用、您可能會收到大量500個內部伺服器錯誤。若要避免這些錯誤、請將一致性控制設為「可用」、除非您需要類似Amazon S3的一致性保證。



 a| 
可用的（最終的頭端作業一致性）
 a| 
其行為與「全新寫入後的讀取」一致性層級相同、但最終只能提供一致的執行方式。如果儲存節點無法使用、則頭端作業的可用度比「全新寫入後的準備」高。不同於Amazon S3一致性保證、僅適用於頭端作業。

|===


=== 回應範例

[listing]
----
HTTP/1.1 200 OK
Date: Fri, 18 Sep 2020 01:02:18 GMT
Connection: CLOSE
Server: StorageGRID/11.5.0
x-amz-request-id: 12345
Content-Length: 127
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Consistency xmlns="http://s3.storagegrid.com/doc/2015-02-01/">read-after-new-write</Consistency>
----
.相關資訊
link:consistency-controls.html["一致性控管"]



== 置入時段一致性要求

「放入庫位一致性」要求可讓您指定要套用至庫位執行作業的一致性層級。

預設的一致性控制項設定為保證新建立物件的寫入後讀取。

您必須具有S3：PuttBucketConsistency權限或帳戶root權限、才能完成此作業。



=== 申請

。 `x-ntap-sg-consistency` 參數必須包含下列其中一個值：

|===
| 一致性控制 | 說明 


 a| 
全部
 a| 
所有節點都會立即接收資料、否則要求將會失敗。



 a| 
強大的全球化技術
 a| 
保證所有站台所有用戶端要求的寫入後讀取一致性。



 a| 
強式網站
 a| 
保證站台內所有用戶端要求的寫入後讀取一致性。



 a| 
全新寫入後讀取
 a| 
（預設）為新物件提供寫入後讀取一致性、並最終確保物件更新一致。提供高可用度與資料保護保證。符合Amazon S3一致性保證。

*附註：*如果您的應用程式在不存在的物件上使用標頭要求、如果一個或多個儲存節點無法使用、您可能會收到大量500個內部伺服器錯誤。若要避免這些錯誤、請將一致性控制設為「可用」、除非您需要類似Amazon S3的一致性保證。



 a| 
可用的（最終的頭端作業一致性）
 a| 
其行為與「全新寫入後的讀取」一致性層級相同、但最終只能提供一致的執行方式。如果儲存節點無法使用、則頭端作業的可用度比「全新寫入後的準備」高。不同於Amazon S3一致性保證、僅適用於頭端作業。

|===
*附註：*一般而言、您應該使用「全新寫入後的讀取」一致性控制值。如果要求無法正常運作、請盡可能變更應用程式用戶端行為。或者、將用戶端設定為針對每個API要求指定一致性控制。只能將貯體層級的一致性控制設定為最後的方法。



=== 申請範例

[source, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-consistency=strong-global HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----
.相關資訊
link:consistency-controls.html["一致性控管"]



== 取得時段上次存取時間要求

「取得時段上次存取時間」要求可讓您決定是否為個別的時區啟用或停用上次存取時間更新。

您必須具有S3：GetBucketLastAccessTime權限或帳戶根權限、才能完成此作業。



=== 申請範例

[source, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-lastaccesstime HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


=== 回應範例

此範例顯示已針對儲存庫啟用上次存取時間更新。

[listing]
----
HTTP/1.1 200 OK
Date: Sat, 29 Nov 2015 01:02:18 GMT
Connection: CLOSE
Server: StorageGRID/10.3.0
x-amz-request-id: 12345
Content-Length: 127
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<LastAccessTime xmlns="http://s3.storagegrid.com/doc/2015-02-01/">enabled
</LastAccessTime>
----


== 將時段放入上次存取時間要求

「放置時段上次存取時間」要求可讓您針對個別的時段啟用或停用上次存取時間更新。停用上次存取時間更新可改善效能、是所有以10.3.0版或更新版本建立之儲存區的預設設定。

您必須擁有儲存區的S3：PuttBucketLastAccessTime權限、或是帳戶root權限、才能完成此作業。


NOTE: 從版本10.3開始StorageGRID 、所有新的儲存庫預設都會停用上次存取時間的更新。如果您有使用StorageGRID 舊版的更新程式建立的儲存區、而且想要符合新的預設行為、則必須明確停用這些舊版儲存區的上次存取時間更新。您可以使用租戶管理程式中的「放置時段上次存取時間」要求、「* S3 *>* Bucket *>*變更上次存取設定*」核取方塊、或「租戶管理API」、來啟用或停用上次存取時間的更新。

如果某個儲存區的上次存取時間更新已停用、則會將下列行為套用至儲存區上的作業：

* 「取得物件」、「取得物件ACL」、「取得物件標記」和「標頭物件要求」不會更新上次存取時間。不會將物件新增至佇列、以進行資訊生命週期管理（ILM）評估。
* 放置物件：只更新中繼資料的複製和放置物件標記要求、也會更新上次存取時間。物件會新增至佇列以進行ILM評估。
* 如果來源儲存區的上次存取時間更新已停用、則「放置物件」-「複製要求」不會更新來源儲存區的上次存取時間。複製的物件不會新增至來源儲存區的ILM評估佇列。但是、對於目的地、「放置物件」-「複製要求」一律會更新上次存取時間。物件複本會新增至佇列以進行ILM評估。
* 完成多重成分上傳要求更新上次存取時間。完成的物件會新增至佇列以進行ILM評估。




=== 申請範例

此範例可讓儲存區的上次存取時間達到。

[source, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-lastaccesstime=enabled HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----
此範例會停用儲存區的上次存取時間。

[source, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-lastaccesstime=disabled HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----
.相關資訊
link:../tenant/index.html["使用租戶帳戶"]



== 刪除時段中繼資料通知組態要求

刪除庫位中繼資料通知組態要求可讓您刪除組態XML、以停用個別庫位的搜尋整合服務。

您必須擁有儲存區的S3：刪除BucketMetadata通知權限、或是帳戶根權限、才能完成此作業。



=== 申請範例

此範例顯示停用區段的搜尋整合服務。

[source, subs="specialcharacters,quotes"]
----
DELETE /test1?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== 取得Bucket中繼資料通知組態要求

「Get Bucket中繼資料」通知組態要求可讓您擷取組態XML、以設定個別儲存區的搜尋整合。

您必須具有S3：GetBucketMetadata通知權限、或是帳戶root、才能完成此作業。



=== 申請範例

此要求會擷取名為的儲存區之中繼資料通知組態 `bucket`。

[source, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


=== 回應

回應本文包含儲存區的中繼資料通知組態。中繼資料通知組態可讓您決定儲存區的搜尋整合設定方式。也就是、它可讓您決定要建立索引的物件、以及要將物件中繼資料傳送至哪個端點。

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:_region:account-ID_:domain/_mydomain/myindex/mytype_</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
每個中繼資料通知組態都包含一或多個規則。每個規則都會指定套用的物件、StorageGRID 以及應將物件中繼資料傳送到哪個目的地。目的地必須使用StorageGRID 不實端點的URN來指定。

|===
| 名稱 | 說明 | 必要 


 a| 
Metadata NotifyationConfiguration
 a| 
用於指定中繼資料通知物件和目的地之規則的容器標籤。

包含一或多個規則元素。
 a| 
是的



 a| 
規則
 a| 
規則的容器標記、用於識別應將中繼資料新增至指定索引的物件。

會拒絕具有重疊前置碼的規則。

包括在Metadata NotifyationConfiguration元素中。
 a| 
是的



 a| 
ID
 a| 
規則的唯一識別碼。

包含在Rule元素中。
 a| 
否



 a| 
狀態
 a| 
狀態可以是「已啟用」或「已停用」。不針對停用的規則採取任何行動。

包含在Rule元素中。
 a| 
是的



 a| 
前置碼
 a| 
符合前置碼的物件會受到規則影響、其中繼資料會傳送到指定的目的地。

若要符合所有物件、請指定一個空白首碼。

包含在Rule元素中。
 a| 
是的



 a| 
目的地
 a| 
規則目的地的容器標記。

包含在Rule元素中。
 a| 
是的



 a| 
urn
 a| 
傳送物件中繼資料的目的地之一。必須是StorageGRID 具有下列屬性的不景端點的URN：

* `es` 必須是第三個元素。
* URN必須以索引結尾、並在表單中輸入中繼資料的儲存位置 `domain-name/myindex/mytype`。


端點是使用租戶管理程式或租戶管理API來設定。它們採用下列形式：

* `arn:aws:es:_region:account-ID_:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


端點必須在提交組態XML之前進行設定、否則組態將會失敗並顯示404錯誤。

目標元素中包含urn.
 a| 
是的

|===


=== 回應範例

之間包含的XML  `<MetadataNotificationConfiguration></MetadataNotificationConfiguration>` 標記顯示如何為儲存區設定與搜尋整合端點的整合。在此範例中、物件中繼資料會傳送至名為的Elasticsearch索引 `current` 並輸入named `2017` 這是以AWS網域命名的 `records`。

[listing]
----
HTTP/1.1 200 OK
Date: Thu, 20 Jul 2017 18:24:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/11.0.0
x-amz-request-id: 3832973499
Content-Length: 264
Content-Type: application/xml

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix>2017</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/records/current/2017</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.相關資訊
link:../tenant/index.html["使用租戶帳戶"]



== 放置時段中繼資料通知組態要求

「置入庫位元資料」通知組態要求可讓您針對個別的庫位啟用搜尋整合服務。您在要求本文中提供的中繼資料通知組態XML、會指定將中繼資料傳送至目的地搜尋索引的物件。

您必須擁有儲存區的S3：PuttBucketMetadata通知權限、或是帳戶根權限、才能完成此作業。



=== 申請

要求必須在要求本文中包含中繼資料通知組態。每個中繼資料通知組態都包含一或多個規則。每個規則都會指定要套用的物件、StorageGRID 以及應將物件中繼資料傳送到哪個目的地。

物件可依物件名稱的前置詞進行篩選。例如、您可以傳送具有前置碼之物件的中繼資料 `/images` 至一個目的地、以及具有前置碼的物件 `/videos` 到另一個。

具有重疊前置碼的組態無效、在提交時會遭到拒絕。例如、含有前置字元物件規則的組態 `test` 和第二個規則、用於具有前置碼的物件 `test2` 不允許。

目的地必須使用StorageGRID 不實端點的URN來指定。當中繼資料通知組態已提交、或要求以失敗的方式提交時、端點必須存在 `400 Bad Request`。錯誤訊息指出： `Unable to save the metadata notification (search) policy. The specified endpoint URN does not exist: _URN_.`

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
下表說明中繼資料通知組態XML中的元素。

|===
| 名稱 | 說明 | 必要 


 a| 
Metadata NotifyationConfiguration
 a| 
用於指定中繼資料通知物件和目的地之規則的容器標籤。

包含一或多個規則元素。
 a| 
是的



 a| 
規則
 a| 
規則的容器標記、用於識別應將中繼資料新增至指定索引的物件。

會拒絕具有重疊前置碼的規則。

包括在Metadata NotifyationConfiguration元素中。
 a| 
是的



 a| 
ID
 a| 
規則的唯一識別碼。

包含在Rule元素中。
 a| 
否



 a| 
狀態
 a| 
狀態可以是「已啟用」或「已停用」。不針對停用的規則採取任何行動。

包含在Rule元素中。
 a| 
是的



 a| 
前置碼
 a| 
符合前置碼的物件會受到規則影響、其中繼資料會傳送到指定的目的地。

若要符合所有物件、請指定一個空白首碼。

包含在Rule元素中。
 a| 
是的



 a| 
目的地
 a| 
規則目的地的容器標記。

包含在Rule元素中。
 a| 
是的



 a| 
urn
 a| 
傳送物件中繼資料的目的地之一。必須是StorageGRID 具有下列屬性的不景端點的URN：

* `es` 必須是第三個元素。
* URN必須以索引結尾、並在表單中輸入中繼資料的儲存位置 `domain-name/myindex/mytype`。


端點是使用租戶管理程式或租戶管理API來設定。它們採用下列形式：

* `arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


端點必須在提交組態XML之前進行設定、否則組態將會失敗並顯示404錯誤。

目標元素中包含urn.
 a| 
是的

|===


=== 申請範例

此範例顯示啟用儲存庫的搜尋整合功能。在此範例中、所有物件的物件中繼資料都會傳送到相同的目的地。

[source, subs="specialcharacters,quotes"]
----
PUT /test1?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix></Prefix>
        <Destination>
           <Urn>urn:sgws:es:::sgws-notifications/test1/all</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
在此範例中、物件的中繼資料會與前置詞相符 `/images` 會傳送至一個目的地、而物件中繼資料則會與前置詞相符 `/videos` 傳送至第二個目的地。

[source, subs="specialcharacters,quotes"]
----
PUT /graphics?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Images-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/images</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/es-domain/graphics/imagetype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Videos-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/videos</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-west-1:22222222:domain/es-domain/graphics/videotype</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.相關資訊
link:../tenant/index.html["使用租戶帳戶"]



=== 由搜尋整合服務產生的JSON

當您啟用儲存區的搜尋整合服務時、每次新增、更新或刪除物件中繼資料或標記時、都會產生Json文件並傳送至目的地端點。

此範例顯示Json範例、該範例可在具有金鑰的物件產生時產生 `SGWS/Tagging.txt` 在名為的儲存區中建立 `test`。。 `test` 儲存區沒有版本、因此 `versionId` 標記為空白。

[listing]
----
{
  "bucket": "test",
  "key": "SGWS/Tagging.txt",
  "versionId": "",
  "accountId": "86928401983529626822",
  "size": 38,
  "md5": "3d6c7634a85436eee06d43415012855",
  "region":"us-east-1"
  "metadata": {
    "age": "25"
  },
  "tags": {
    "color": "yellow"
  }
}
----


=== 中繼資料通知中包含的物件中繼資料

此表格列出JSON文件中所有欄位、這些欄位會在啟用搜尋整合時傳送至目的地端點。

文件名稱包含儲存區名稱、物件名稱及版本ID（若有）。

|===
| 類型 | 項目名稱 | 說明 


 a| 
儲存區和物件資訊
 a| 
鏟斗
 a| 
庫位名稱



 a| 
儲存區和物件資訊
 a| 
金鑰
 a| 
物件金鑰名稱



 a| 
儲存區和物件資訊
 a| 
版本ID
 a| 
物件版本、適用於版本控制的儲存區中的物件



 a| 
儲存區和物件資訊
 a| 
區域
 a| 
例如、儲存區 `us-east-1`



 a| 
系統中繼資料
 a| 
尺寸
 a| 
HTTP用戶端可見的物件大小（以位元組為單位）



 a| 
系統中繼資料
 a| 
md5
 a| 
物件雜湊



 a| 
使用者中繼資料
 a| 
中繼資料
`_key:value_`
 a| 
物件的所有使用者中繼資料、做為金鑰值配對



 a| 
標記
 a| 
標記
`_key:value_`
 a| 
為物件定義的所有物件標記、做為金鑰值配對

|===
*附註：* StorageGRID 針對標記和使用者中繼資料、將日期和數字以字串或S3事件通知的形式傳遞給Elasticsearch。若要設定Elasticsearch將這些字串解譯為日期或數字、請遵循Elasticsearch指示進行動態欄位對應、以及對應日期格式。您必須先在索引上啟用動態欄位對應、才能設定搜尋整合服務。建立文件索引之後、就無法在索引中編輯文件的欄位類型。



== 取得儲存使用量要求

「Get Storage使用量」要求會告訴您某個帳戶所使用的總儲存容量、以及與該帳戶相關聯的每個儲存區容量。

帳戶使用的儲存容量及其儲存桶、可透過修改後的Get Service（取得服務）要求取得 `x-ntap-sg-usage` 查詢參數。儲存區的使用量會與系統處理的PUT和DELETE要求分開追蹤。使用值可能會在處理要求時延遲、使其符合預期值、尤其是系統負載過重時。

根據預設StorageGRID 、功能區會嘗試使用強大的全域一致性來擷取使用資訊。如果無法達到強大的全球一致性、StorageGRID 則嘗試以強大的站台一致性擷取使用資訊。

您必須具有S3：listAllMyb桶 權限、或是帳戶root、才能完成此作業。



=== 申請範例

[source, subs="specialcharacters,quotes"]
----
GET /?x-ntap-sg-usage HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


=== 回應範例

此範例顯示一個帳戶、其中兩個儲存區中有四個物件和12個位元組的資料。每個儲存區包含兩個物件和六個位元組的資料。

[listing]
----
HTTP/1.1 200 OK
Date: Sat, 29 Nov 2015 00:49:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/10.2.0
x-amz-request-id: 727237123
Content-Length: 427
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<UsageResult xmlns="http://s3.storagegrid.com/doc/2015-02-01">
<CalculationTime>2014-11-19T05:30:11.000000Z</CalculationTime>
<ObjectCount>4</ObjectCount>
<DataBytes>12</DataBytes>
<Buckets>
<Bucket>
<Name>bucket1</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
<Bucket>
<Name>bucket2</Name>
<ObjectCount>2</ObjectCount>
<DataBytes>6</DataBytes>
</Bucket>
</Buckets>
</UsageResult>
----


=== 版本管理

儲存的每個物件版本都有助於 `ObjectCount` 和 `DataBytes` 回應中的值。刪除標記不會新增至 `ObjectCount` 總計。

.相關資訊
link:consistency-controls.html["一致性控管"]



== 已過時的資源桶要求、適用於舊版法規遵循

您可能需要使用StorageGRID Sfs3 REST API來管理使用舊版Compliance功能所建立的儲存區。



=== 法規遵循功能已過時

先前版本的不支援《支援不符合要求》功能、現已由S3物件鎖定取代。StorageGRID StorageGRID

如果您先前已啟用「全域規範」設定、當您升級StorageGRID 至版本號為「版本5：11：5」時、全域「S3物件鎖定」設定會自動啟用。您不再能夠在啟用「法規遵循」的情況下建立新的儲存庫、不過、您可以視需要使用StorageGRID 「S3 REST API」來管理任何現有的符合舊規範的儲存庫。

link:s3-rest-api-supported-operations-and-limitations.html["使用S3物件鎖定"]

link:../ilm/index.html["使用ILM管理物件"]

https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp知識庫：如何管理StorageGRID 支援老舊的知識庫、請參閱《知識庫文章"]



=== 已過時：將資源桶要求修改以符合法規要求

SGCompliance XML元素已過時。先前、您可以將StorageGRID 此等不必要的自訂元素納入可選的XML要求內容中、以建立符合法規的儲存庫要求。


IMPORTANT: 先前版本的不支援《支援不符合要求》功能、現已由S3物件鎖定取代。StorageGRID StorageGRID

link:s3-rest-api-supported-operations-and-limitations.html["使用S3物件鎖定"]

link:../ilm/index.html["使用ILM管理物件"]

https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp知識庫：如何管理StorageGRID 支援老舊的知識庫、請參閱《知識庫文章"]

您無法再建立啟用「法規遵循」的新庫位。如果您嘗試使用「置放桶」要求修改以符合法規要求、以建立新的「符合法規」桶、則會傳回下列錯誤訊息：

[listing]
----
The Compliance feature is deprecated.
Contact your StorageGRID administrator if you need to create new Compliant buckets.
----
.相關資訊
link:../ilm/index.html["使用ILM管理物件"]

link:../tenant/index.html["使用租戶帳戶"]



=== 已過時：Get Bucket Compliance要求

Get Bucket法規遵循要求已過時。不過、您可以繼續使用此要求來判斷現有舊版相容儲存區目前有效的法規遵循設定。


IMPORTANT: 先前版本的不支援《支援不符合要求》功能、現已由S3物件鎖定取代。StorageGRID StorageGRID

link:s3-rest-api-supported-operations-and-limitations.html["使用S3物件鎖定"]

link:../ilm/index.html["使用ILM管理物件"]

https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp知識庫：如何管理StorageGRID 支援老舊的知識庫、請參閱《知識庫文章"]

您必須具有S3：GetBucketCompliance權限、或是帳戶root、才能完成此作業。



==== 申請範例

此範例要求可讓您決定名為的儲存區的法規遵循設定 `mybucket`。

[source, subs="specialcharacters,quotes"]
----
GET /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


==== 回應範例

在回應XML中、 `<SGCompliance>` 列出庫位有效的法規遵循設定。此回應範例顯示儲存區的法規遵循設定、其中每個物件將保留一年（525600分鐘）、從物件擷取到網格開始算起。此庫位目前沒有合法持有。每個物件將在一年後自動刪除。

[source, subs="specialcharacters,quotes"]
----
HTTP/1.1 200 OK
Date: _date_
Connection: _connection_
Server: StorageGRID/11.1.0
x-amz-request-id: _request ID_
Content-Length: _length_
Content-Type: application/xml

<SGCompliance>
  <RetentionPeriodMinutes>525600</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
|===
| 名稱 | 說明 


 a| 
RetentionPeriodMinutes
 a| 
新增至此儲存區之物件的保留期間長度（以分鐘為單位）。保留期間是從物件擷取至網格時開始。



 a| 
LegalHold
 a| 
* 是：此儲存庫目前處於合法持有狀態。在取消合法持有之前、即使保留期間已過期、也無法刪除此儲存區中的物件。
* 假：此庫位目前未合法持有。此儲存區中的物件可在保留期間到期時刪除。




 a| 
自動刪除
 a| 
* 是：此儲存區中的物件會在保留期間到期時自動刪除、除非儲存區處於合法持有狀態。
* 否：保留期間到期時、此儲存區中的物件不會自動刪除。如果需要刪除這些物件、您必須手動刪除這些物件。


|===


==== 錯誤回應

如果儲存區建立不符合法規要求、則回應的HTTP狀態代碼為 `404 Not Found`的S3錯誤代碼 `XNoSuchBucketCompliance`。

.相關資訊
link:../ilm/index.html["使用ILM管理物件"]

link:../tenant/index.html["使用租戶帳戶"]



=== 已過時：提出資源桶法規遵循要求

「放入時段」法規遵循要求已過時。不過、您可以繼續使用此要求來修改現有舊版相容桶的法規遵循設定。例如、您可以將現有的貯體置於合法持有狀態、或是延長保留期間。


IMPORTANT: 先前版本的不支援《支援不符合要求》功能、現已由S3物件鎖定取代。StorageGRID StorageGRID

link:s3-rest-api-supported-operations-and-limitations.html["使用S3物件鎖定"]

link:../ilm/index.html["使用ILM管理物件"]

https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp知識庫：如何管理StorageGRID 支援老舊的知識庫、請參閱《知識庫文章"]

您必須具有S3：PuttBucketCompliance權限、或是帳戶root、才能完成此作業。

在發出「放入庫位」法規遵循要求時、您必須為法規遵循設定的每個欄位指定一個值。



==== 申請範例

此範例要求會修改名為的儲存區的規範設定 `mybucket`。在此範例中、物件位於 `mybucket` 現在將保留兩年（1、051、200分鐘）、而非一年、從物件進入網格開始算起。此庫位沒有合法持有。每個物件將在兩年後自動刪除。

[source, subs="specialcharacters,quotes"]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization name_
Host: _host_
Content-Length: 152

<SGCompliance>
  <RetentionPeriodMinutes>1051200</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
|===
| 名稱 | 說明 


 a| 
RetentionPeriodMinutes
 a| 
新增至此儲存區之物件的保留期間長度（以分鐘為單位）。保留期間是從物件擷取至網格時開始。

*注意：*當為RetentionPeriodMinute指定新值時、您必須指定等於或大於該儲存格目前保留期間的值。在桶的保留期間設定完成之後、您就無法減少該值、只能增加該值。



 a| 
LegalHold
 a| 
* 是：此儲存庫目前處於合法持有狀態。在取消合法持有之前、即使保留期間已過期、也無法刪除此儲存區中的物件。
* 假：此庫位目前未合法持有。此儲存區中的物件可在保留期間到期時刪除。




 a| 
自動刪除
 a| 
* 是：此儲存區中的物件會在保留期間到期時自動刪除、除非儲存區處於合法持有狀態。
* 否：保留期間到期時、此儲存區中的物件不會自動刪除。如果需要刪除這些物件、您必須手動刪除這些物件。


|===


==== 法規遵循設定的一致性層級

當您更新S3儲存區的法規遵循設定、並提出「置放儲存區法規遵循」要求時StorageGRID 、即可嘗試更新整個網格的儲存區中繼資料。根據預設、StorageGRID 支援使用*強式全域*一致性層級、以保證所有資料中心站台及包含儲存庫中繼資料的所有儲存節點、在變更的法規遵循設定中、具有寫入後讀取一致性。

如果StorageGRID 由於某個站台的資料中心站台或多個儲存節點無法使用、導致無法達到*強式全域*一致性等級、則回應的HTTP狀態代碼為 `503 Service Unavailable.`

如果您收到此回應、則必須聯絡網格管理員、以確保所需的儲存服務能夠儘快提供。如果網格管理員無法在每個站台上提供足夠的儲存節點、技術支援可能會強制*強站台*一致性層級、引導您重試失敗的要求。


IMPORTANT: 除非您是技術支援人員的指示、而且您不瞭解使用此層級可能造成的後果、否則請勿強迫*強站台*一致性層級以符合放置桶規範。

當一致性層級降至*強站台*時StorageGRID 、更新的法規遵循設定只有在站台內的用戶端要求才具有寫入後讀取一致性。這表示StorageGRID 在所有站台和儲存節點都可用之前、此儲存區的設定可能會暫時有多個不一致的設定。不一致的設定可能會導致非預期和非預期的行為。例如、如果您將儲存庫置於合法持有之下、而強制降低一致性層級、則儲存庫先前的法規遵循設定（即合法暫停）可能會繼續在某些資料中心站台上生效。因此、您認為合法保留的物件、可能會在保留期間到期時遭到刪除、使用者或自動刪除（如果已啟用）。

若要強制使用*強站台*一致性層級、請重新發出「Put Bucket Compliance」（放入儲存庫）要求、並附上 `Consistency-Control` HTTP要求標頭、如下所示：

[listing]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Consistency-Control: strong-site
----


==== 錯誤回應

* 如果儲存區建立不符合法規要求、則回應的HTTP狀態代碼為 `404 Not Found`。
* 如果 `RetentionPeriodMinutes` 在要求中、HTTP狀態代碼小於儲存區目前的保留期間 `400 Bad Request`。


.相關資訊
link:storagegrid-s3-rest-api-operations.html["已過時：將資源桶要求修改以符合法規要求"]

link:../tenant/index.html["使用租戶帳戶"]

link:../ilm/index.html["使用ILM管理物件"]
