---
permalink: monitor/generating-text-reports.html 
sidebar: sidebar 
keywords: reports, text 
summary: 文字報告會顯示NMS服務已處理之屬性資料值的文字呈現。您可以報告資料中心站台、網格節點、元件或服務。 
---
= 產生文字報告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
文字報告會顯示NMS服務已處理之屬性資料值的文字呈現。您可以報告資料中心站台、網格節點、元件或服務。

.您需要的產品
* 您必須使用支援的瀏覽器登入Grid Manager。
* 您必須擁有特定的存取權限。


.關於這項工作
對於預期會持續變更的屬性資料、此屬性資料會定期由NMS服務（來源）取樣。對於不常變更的屬性資料（例如、以狀態或狀態變更等事件為基礎的資料）、當值變更時、會將屬性值傳送至NMS服務。

顯示的報告類型取決於設定的時間週期。根據預設、會針對超過一週的時間段產生Aggregate文字報告。

灰色文字表示服務在取樣期間以管理方式關閉。藍色文字表示服務處於未知狀態。

.步驟
. 選取*支援*>*工具*>*網格拓撲*。
. 選擇*網格節點_*>*元件或服務_*>*報告*>*文字*。
. 從「*屬性*」下拉式清單中選取要報告的屬性。
. 從*每頁結果數*下拉式清單中選取每頁結果數。
. 若要將值四捨五入至最多三個小數位數（例如、報告為百分比的屬性）、請取消選取「*原始資料*」核取方塊。
. 從「*快速查詢*」下拉式清單中選取要報告的時段。
+
選取「自訂查詢」選項以選取特定時間範圍。

+
報告會在幾分鐘後出現。請等待數分鐘、以製作長時間範圍的表格。

. 如果您選取「自訂查詢」、則必須輸入*開始日期*和*結束日期*來自訂報告的期間。
+
使用格式 `YYYY/MM/DDHH:MM:SS` 本地時間。必須輸入前置零以符合格式。例如2017年4月6日7：30：00驗證失敗。正確格式為：2017年4月6日07：30：00。

. 按一下 * 更新 * 。
+
稍後會產生一份文字報告。請等待數分鐘、以製作長時間範圍的表格。根據查詢設定的時間長度、會顯示原始文字報告或彙總文字報告。

. 如果您要列印報告、請按一下滑鼠右鍵並選取*「Print」（列印）*、然後修改任何必要的印表機設定、再按一下「* Print」（列印）*。

