---
permalink: maintain/checking-data-repair-jobs.html 
sidebar: sidebar 
keywords: storagegrid, data repair 
summary: 在解除委任網格節點之前、您必須確認沒有任何資料修復工作處於作用中狀態。如果有任何修復失敗、您必須重新啟動它們、並讓它們在執行取消委任程序之前完成。 
---
= 正在檢查資料修復工作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在解除委任網格節點之前、您必須確認沒有任何資料修復工作處於作用中狀態。如果有任何修復失敗、您必須重新啟動它們、並讓它們在執行取消委任程序之前完成。

如果您需要取消委任已中斷連線的儲存節點、也會在取消委任程序完成後完成這些步驟、以確保資料修復工作已成功完成。您必須確保已移除節點上的任何銷毀編碼片段已成功還原。

這些步驟僅適用於具有銷毀編碼物件的系統。

. 登入主要管理節點：
+
.. 輸入下列命令： `ssh admin@_grid_node_IP_`
+
當您以root登入時、提示會從變更 `$` 至 `#`。

.. 輸入中所列的密碼 `Passwords.txt` 檔案：
.. 輸入下列命令以切換至root： `su -`
.. 輸入中所列的密碼 `Passwords.txt` 檔案：


. 檢查執行中的修復： `repair-data show-ec-repair-status`
+
** 如果您從未執行資料修復工作、則輸出為 `No job found`。您不需要重新啟動任何修復工作。
** 如果資料修復工作先前執行或目前正在執行、則輸出會列出修復的資訊。每項維修都有唯一的維修ID。前往下一步。


+
[listing]
----
root@DC1-ADM1:~ # repair-data show-ec-repair-status

Repair ID Scope Start Time End Time State Est/Affected Bytes Repaired Retry Repair
===================================================================================
949283 DC1-S-99-10(Volumes: 1,2) 2016-11-30T15:27:06.9 Success 17359 17359 No
949292 DC1-S-99-10(Volumes: 1,2) 2016-11-30T15:37:06.9 Failure 17359 0     Yes
949294 DC1-S-99-10(Volumes: 1,2) 2016-11-30T15:47:06.9 Failure 17359 0     Yes
949299 DC1-S-99-10(Volumes: 1,2) 2016-11-30T15:57:06.9 Failure 17359 0     Yes
----
. 如果所有維修的州/省為 `Success`、您不需要重新啟動任何修復工作。
. 如果維修所在的州為 `Failure`、您必須重新啟動該修復。
+
.. 從輸出中取得故障修復的修復ID。
.. 執行 `repair-data start-ec-node-repair` 命令。
+
使用 `--repair-id` 選項以指定修復ID。例如、如果您要重試維修ID為949292的修復、請執行下列命令： `repair-data start-ec-node-repair --repair-id 949292`

.. 繼續追蹤EC資料維修的狀態、直到所有維修的州為止 `Success`。



