---
permalink: maintain/fixing-missing-block-device-errors.html 
sidebar: sidebar 
keywords: storagegrid, missing block device, block device error 
summary: '系統會檢查每個還原的節點是否對應到有效的區塊裝置特殊檔案、或是區塊裝置特殊檔案的有效軟體連結。如果StorageGRID 在中找到無效的對應 `/etc/storagegrid/nodes/_node-name_.conf` 檔案、顯示遺失的區塊裝置錯誤。' 
---
= 修正遺失的區塊裝置錯誤
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
系統會檢查每個還原的節點是否對應到有效的區塊裝置特殊檔案、或是區塊裝置特殊檔案的有效軟體連結。如果StorageGRID 在中找到無效的對應 `/etc/storagegrid/nodes/_node-name_.conf` 檔案、顯示遺失的區塊裝置錯誤。

如果您發現與此模式相符的錯誤：

`Checking configuration file /etc/storagegrid/nodes/_node-name_.conf for node _node-name_...`
`ERROR: _node-name_: BLOCK_DEVICE_PURPOSE = _path-name_`_'節點名稱_：_path-name_不存在'

這意味著 `/etc/storagegrid/nodes/_node-name_.conf` 將_node-name_用於目的的區塊裝置對應至Linux檔案系統中的指定路徑名稱、但該位置沒有有效的區塊裝置特殊檔案或區塊裝置特殊檔案的軟體連結。

確認您已完成「部署新的Linux主機」中的步驟。對所有區塊裝置使用與原始主機相同的持續裝置名稱。

如果您無法還原或重新建立遺失的區塊裝置特殊檔案、您可以配置適當大小和儲存類別的新區塊裝置、並編輯節點組態檔、以變更block_device_pur用意 的值、以指向新的區塊裝置特殊檔案。

請從Linux作業系統安裝說明「儲存需求」一節的表格中、判斷適當的大小和儲存類別。請先檢閱「設定主機儲存設備」中的建議、再繼續更換區塊裝置。


IMPORTANT: 如果您必須為任何組態檔案變數提供新的區塊儲存設備、請從開始 `BLOCK_DEVICE_` 由於故障主機遺失原始區塊裝置、因此在嘗試進一步的還原程序之前、請先確認新的區塊裝置未格式化。如果您使用共享儲存設備並已建立新的Volume、則新的區塊裝置將不會格式化。如果您不確定、請針對任何新的區塊儲存設備特殊檔案執行下列命令。


CAUTION: 僅針對新的區塊儲存裝置執行下列命令。如果您認為區塊儲存設備仍包含要還原之節點的有效資料、請勿執行此命令、因為裝置上的任何資料都會遺失。

[listing]
----
sudo dd if=/dev/zero of=/dev/mapper/my-block-device-name bs=1G count=1
----
.相關資訊
link:deploying-new-linux-hosts.html["部署新的Linux主機"]

link:../rhel/index.html["安裝Red Hat Enterprise Linux或CentOS"]

link:../ubuntu/index.html["安裝Ubuntu或DEBIAN"]
