---
permalink: maintain/restoring-audit-log-on-recovered-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore audit log, non-primary admin node 
summary: 如果您能夠從故障的非主要管理節點保留稽核記錄、以便保留歷史稽核記錄資訊、您可以將其複製到您要恢復的非主要管理節點。 
---
= 在恢復的非主要管理節點上還原稽核記錄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您能夠從故障的非主要管理節點保留稽核記錄、以便保留歷史稽核記錄資訊、您可以將其複製到您要恢復的非主要管理節點。

* 恢復的管理節點必須安裝並執行。
* 在原始管理節點失敗之後、您必須將稽核記錄複製到其他位置。


如果管理節點失敗、儲存至該管理節點的稽核記錄可能會遺失。您可以從故障的管理節點複製稽核記錄、然後將這些稽核記錄還原至恢復的管理節點、以避免資料遺失。視故障而定、可能無法從故障的管理節點複製稽核記錄。在這種情況下、如果部署有多個管理節點、您可以從另一個管理節點恢復稽核記錄、因為稽核記錄會複寫到所有管理節點。

如果只有一個管理節點、而且無法從故障節點複製稽核記錄、則恢復的管理節點會開始將事件記錄到稽核記錄、就像是新安裝一樣。

您必須盡快恢復管理節點、才能還原記錄功能。

. 登入恢復的管理節點：
+
.. 輸入下列命令：+
`ssh admin@recovery_Admin_Node_IP`
.. 輸入中所列的密碼 `Passwords.txt` 檔案：
.. 輸入下列命令以切換至root： `su -`
.. 輸入中所列的密碼 `Passwords.txt` 檔案：


+
以root登入之後、提示會從變更 `$` 至 `#`。

. 檢查哪些稽核檔案已保留：
+
`cd /var/local/audit/export`

. 將保留的稽核記錄檔複製到恢復的管理節點：
+
`scp admin@grid_node_IP:/var/local/tmp/saved-audit-logs/YYYY*`

+
出現提示時、輸入admin的密碼。

. 為了安全起見、請在確認已成功複製稽核記錄到恢復的管理節點之後、從故障的網格節點刪除這些記錄。
. 更新已恢復管理節點上稽核記錄檔的使用者和群組設定：
+
`chown ams-user:bycast *`

. 以root登出： `exit`


您也必須還原稽核共用的任何既有用戶端存取權。如需詳細資訊、請參閱《關於管理StorageGRID 功能的說明》。

.相關資訊
link:../admin/index.html["管理StorageGRID"]
