---
permalink: maintain/restoring-and-validating-grid-nodes.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore grid node, restore node, validate grid node, validate node 
summary: 您必須還原任何故障網格節點的網格組態檔、然後驗證網格組態檔並解決任何錯誤。 
---
= 還原及驗證網格節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須還原任何故障網格節點的網格組態檔、然後驗證網格組態檔並解決任何錯誤。

.關於這項工作
您可以匯入主機上應該存在的任何網格節點、只要它存在 `/var/local` 磁碟區不會因為先前主機的故障而遺失。例如、 `/var/local` 如果您使用共享儲存設備來StorageGRID 儲存靜態系統資料磁碟區、則仍可能存在Volume、如StorageGRID Linux作業系統的《安裝說明》所述。匯入節點會將其節點組態檔還原至主機。

如果無法匯入遺失的節點、則必須重新建立其網格組態檔。

然後您必須驗證網格組態檔案、並解決任何可能發生的網路或儲存問題、才能繼續重新啟動StorageGRID 更新。當您重新建立節點的組態檔時、您必須使用與您要還原之節點相同的替換節點名稱。

如需位置的詳細資訊、請參閱安裝說明 `/var/local` 節點的Volume。

.步驟
. 在恢復主機的命令列中、列出所有目前設定StorageGRID 的電網節點：``sudo storagegrid node list``
+
如果未設定任何網格節點、則不會有任何輸出。如果已設定某些網格節點、則預期輸出格式如下：

+
[listing]
----
Name               Metadata-Volume
================================================================
dc1-adm1           /dev/mapper/sgws-adm1-var-local
dc1-gw1            /dev/mapper/sgws-gw1-var-local
dc1-sn1            /dev/mapper/sgws-sn1-var-local
dc1-arc1           /dev/mapper/sgws-arc1-var-local
----
+
如果未列出應在主機上設定的部分或全部網格節點、則需要還原遺失的網格節點。

. 匯入具有的網格節點 `/var/local` Volume：
+
.. 針對您要匯入的每個節點執行下列命令：``sudo storagegrid node import node-var-local-volume-path``
+
。 `storagegrid node import` 只有在目標節點上次執行時、命令才會在其主機上正常關機。如果情況並非如此、您將會發現類似下列的錯誤：

+
`This node (_node-name_) appears to be owned by another host (UUID host-uuid).`

+
`Use the --force flag if you are sure import is safe.`

.. 如果您看到另一部主機擁有的節點錯誤、請再次使用執行命令 `--force` 完成匯入的旗標：``sudo storagegrid --force node import node-var-local-volume-path``
+

NOTE: 任何使用匯入的節點 `--force` 旗標需要額外的恢復步驟、才能重新加入網格、如「執行額外的恢復步驟（如有需要）」所述。



. 適用於沒有的網格節點 `/var/local` 磁碟區、重新建立節點的組態檔、將其還原至主機。
+
請遵循安裝說明中「creating node configuration files'（建立節點組態檔）」中的準則。

+

IMPORTANT: 當您重新建立節點的組態檔時、您必須使用與您要還原之節點相同的替換節點名稱。對於Linux部署、請確定組態檔名稱包含節點名稱。您應該盡可能使用相同的網路介面、區塊裝置對應和IP位址。這種做法可將恢復期間需要複製到節點的資料量降至最低、這可能會使恢復速度大幅加快（在某些情況下、是幾分鐘而非數週）。

+

IMPORTANT: 如果您使用任何新的區塊裝置（StorageGRID 以前未曾使用過的裝置）作為任何組態變數的值、則以該組態變數開頭 `BLOCK_DEVICE_` 當您重新建立節點的組態檔時、請務必遵循「修復遺失的區塊裝置錯誤」中的所有準則。

. 在恢復的主機上執行下列命令、列出所有StorageGRID 的支援節點。
+
`sudo storagegrid node list`

. 驗證StorageGRID 每個網格節點的節點組態檔、其名稱會顯示在「節點清單」輸出中：
+
`sudo storagegrid node validate _node-name_`

+
您必須先解決任何錯誤或警告、才能開始StorageGRID 執行「支援服務」。以下各節將詳細說明在恢復期間可能具有特殊意義的錯誤。



.相關資訊
link:../rhel/index.html["安裝Red Hat Enterprise Linux或CentOS"]

link:../ubuntu/index.html["安裝Ubuntu或DEBIAN"]

link:fixing-mssing-network-interface-errors.html["修正遺失的網路介面錯誤"]

link:fixing-missing-block-device-errors.html["修正遺失的區塊裝置錯誤"]

link:whats-next-performing-additional-recovery-steps-if-required.html["接下來：視需要執行其他恢復步驟"]
