---
permalink: ilm/comparing-s3-object-lock-to-legacy-compliance.html 
sidebar: sidebar 
keywords:  
summary:  
---
= 比較S3物件鎖定與舊版法規遵循
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3物件鎖定功能StorageGRID 取代先前StorageGRID 版本的支援功能。由於新的S3物件鎖定功能符合Amazon S3的要求、因此取代了專屬StorageGRID 的「不符合要求」功能、這項功能現在稱為「舊版法規遵循」。

如果您先前已啟用「全域規範」設定、則當您升級StorageGRID 至還原11.5時、新的全域S3物件鎖定設定會自動啟用。租戶使用者將不再能夠建立StorageGRID 更新的儲存庫、而在啟用了《支援一致性》功能的情況下、於執行下列工作時、租戶使用者仍可繼續使用及管理任何現有的舊有規範儲存庫：

* 將新物件加入已啟用舊版法規遵循的現有儲存區。
* 延長已啟用舊版法規遵循的現有儲存庫的保留期間。
* 變更已啟用舊版法規遵循的現有儲存區的自動刪除設定。
* 合法持有已啟用舊版法規遵循的現有儲存庫。
* 解除合法持有。


https://["NetApp知識庫：如何管理StorageGRID 支援老舊的知識庫、請參閱《知識庫文章"^]

如果您使用StorageGRID 舊版的更新版本的支援功能、請參閱下表、瞭解其與StorageGRID 更新版本中S3物件鎖定功能的比較。

[cols="1a,1a,1a"]
|===
|  | S3物件鎖定（新增） | 法規遵循（舊版） 


 a| 
如何在全域啟用此功能？
 a| 
在Grid Manager中，選擇* Configuration *>* System Settings*>* S3 Object Lock*。
 a| 
不再支援。

*附註：*如果您先前已啟用「全域符合性」設定、當您升級StorageGRID 至「支援範圍」11.5時、全域「S3物件鎖定」設定將會自動啟用。



 a| 
此功能如何啟用儲存庫？
 a| 
使用者必須啟用S3物件鎖定、才能使用租戶管理程式、租戶管理API或S3 REST API建立新的儲存區。
 a| 
使用者無法再建立已啟用「符合性」的新儲存區、但仍可繼續將新物件新增至現有的「符合性」儲存區。



 a| 
是否支援儲存區版本管理？
 a| 
是的。儲存區版本設定是必要的、且會在啟用儲存區的S3物件鎖定時自動啟用。
 a| 
不可以舊版法規遵循功能不允許庫位版本管理。



 a| 
如何設定物件保留？
 a| 
使用者可以為每個物件版本設定保留截止日期。
 a| 
使用者必須為整個儲存庫設定保留期間。保留期間適用於貯體中的所有物件。



 a| 
桶是否有保留和合法持有的預設設定？
 a| 
不可以啟用S3物件鎖定的支援區沒有預設保留期間StorageGRID 。您可以針對每個物件版本指定保留截止日期。
 a| 
是的



 a| 
保留期間可以變更嗎？
 a| 
物件版本的保留截止日期可以增加、但不會減少。
 a| 
可延長庫位的保留期間、但不會縮短。



 a| 
合法持有控制在哪裡？
 a| 
使用者可以合法持有或撤銷貯體中任何物件版本的合法持有。
 a| 
合法持有會置於貯體上、並影響貯體中的所有物件。



 a| 
何時可以刪除物件？
 a| 
物件版本可在達到保留截止日期後刪除、前提是物件未處於合法持有狀態。
 a| 
保留期間到期後、如果儲存區未處於合法保留狀態、則可刪除物件。物件可以自動或手動刪除。



 a| 
是否支援庫位生命週期組態？
 a| 
是的
 a| 
否

|===