---
permalink: fabricpool/best-practices-for-high-availability-groups.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, active-active, active-backup, cloud tier, best practices 
summary: 在將StorageGRID 「靜態FabricPool 」附加為「靜態雲端層」之前、您可以使用StorageGRID 「The SeseGrid Manager」來設定高可用度（HA）群組。 
---
= 高可用度群組的最佳實務做法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在將StorageGRID 「靜態FabricPool 」附加為「靜態雲端層」之前、您可以使用StorageGRID 「The現象網格管理程式」來設定高可用度（HA）群組。



== 什麼是高可用度（HA）群組

為了確保負載平衡器服務永遠可用於管理FabricPool 效益資料、您可以將多個管理和閘道節點的網路介面分組為單一實體、稱為高可用度（HA）群組。如果HA群組中的作用中節點故障、群組中的另一個節點可以繼續管理工作負載。

每個HA群組都提供高可用度的存取權限、可存取相關節點上的共享服務。例如、由所有管理節點組成的HA群組、可提供對部分管理節點管理服務和負載平衡器服務的高可用度存取。僅由閘道節點或管理節點和閘道節點組成的HA群組、可提供對共享負載平衡器服務的高可用度存取。

建立HA群組時、請選取屬於Grid Network（eth0）或Client Network（eth2）的網路介面。HA群組中的所有介面都必須位於相同的網路子網路內。

HA群組會維護一個或多個虛擬IP位址、這些位址會新增至群組的作用中介面。如果作用中介面無法使用、虛擬IP位址會移至另一個介面。此容錯移轉程序通常只需幾秒鐘、而且速度足夠快、用戶端應用程式只會遇到些微影響、而且可以仰賴正常的重試行為來繼續作業。

如果您設定HA負載平衡節點群組、FabricPool 則VMware會連線至該HA群組的虛擬IP位址。



== 高可用度（HA）群組的最佳實務做法

建立StorageGRID 一套適用於FabricPool 功能不實的功能不一的最佳實務做法取決於工作負載、如下所示：

* 如果您計畫FabricPool 搭配主要工作負載資料使用方面、則必須建立至少包含兩個負載平衡節點的HA群組、以避免資料擷取中斷。
* 如果您計畫使用FabricPool 僅供Snapshot使用的磁碟區分層原則或非主要的本機效能層（例如災難恢復位置或NetApp SnapMirror®目的地）、則只能設定一個節點的HA群組。


這些指示說明如何設定主動備份HA的HA群組（一個節點為作用中、一個節點為備份）。不過、您可能偏好使用DNS循環配置資源或主動式HA。若要瞭解這些其他HA組態的優點、請參閱 link:../admin/configuration-options-for-ha-groups.html["HA群組的組態選項"]。
